# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Tue Aug 13 13:58:00 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
from option import option
import common, extract

class Ui_Form(QtCore.QObject):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280,800)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(-1,-1,1281,811))
        font = QtGui.QFont()
        font.setFamily("나눔고딕코딩")
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")

        ######################### 영상 추출 tab
        self.tab_ext = QtWidgets.QWidget()
        self.tab_ext.setObjectName("tab_ext")
        self.ext_tableWidget = QtWidgets.QTableWidget(self.tab_ext)
        self.ext_tableWidget.setGeometry(QtCore.QRect(700,90,571,291))
        self.ext_tableWidget.setObjectName("ext_tableWidget")
        self.ext_tableWidget.setColumnCount(6)
        self.ext_tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setVerticalHeaderItem(0,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setVerticalHeaderItem(1,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setVerticalHeaderItem(2,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setVerticalHeaderItem(3,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setHorizontalHeaderItem(0,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setHorizontalHeaderItem(1,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setHorizontalHeaderItem(2,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setHorizontalHeaderItem(3,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setHorizontalHeaderItem(4,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setHorizontalHeaderItem(5,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(0,0,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(0,1,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(0,2,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(0,3,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(0,4,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(0,5,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(1,0,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(1,1,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(1,2,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(1,3,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(1,4,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(1,5,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(2,0,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(2,1,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(2,2,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(2,3,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(2,4,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(2,5,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(3,0,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(3,1,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(3,2,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(3,3,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(3,4,item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget.setItem(3,5,item)
        self.ext_frame = QtWidgets.QFrame(self.tab_ext)
        self.ext_frame.setGeometry(QtCore.QRect(0,80,671,441))
        self.ext_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ext_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ext_frame.setObjectName("ext_frame")
        self.ext_label = QtWidgets.QLabel(self.ext_frame)
        self.ext_label.setGeometry(QtCore.QRect(10,10,661,421))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.ext_label.setFont(font)
        self.ext_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ext_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ext_label.setObjectName("ext_label")
        self.ext_label_2 = QtWidgets.QLabel(self.tab_ext)
        self.ext_label_2.setGeometry(QtCore.QRect(700,60,121,31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.ext_label_2.setFont(font)
        self.ext_label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ext_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ext_label_2.setObjectName("ext_label_2")
        self.ext_label_3 = QtWidgets.QLabel(self.tab_ext)
        self.ext_label_3.setGeometry(QtCore.QRect(700,550,181,31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.ext_label_3.setFont(font)
        self.ext_label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ext_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.ext_label_3.setObjectName("ext_label_3")
        self.ext_pushButton = QtWidgets.QPushButton(self.tab_ext)
        self.ext_pushButton.setGeometry(QtCore.QRect(698,410,71,28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ext_pushButton.setFont(font)
        self.ext_pushButton.setObjectName("ext_pushButton")
        self.ext_pushButton_2 = QtWidgets.QPushButton(self.tab_ext)
        self.ext_pushButton_2.setGeometry(QtCore.QRect(1160,410,111,28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ext_pushButton_2.setFont(font)
        self.ext_pushButton_2.setObjectName("ext_pushButton_2")
        self.ext_pushButton_3 = QtWidgets.QPushButton(self.tab_ext)
        self.ext_pushButton_3.setGeometry(QtCore.QRect(1038,410,111,28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ext_pushButton_3.setFont(font)
        self.ext_pushButton_3.setObjectName("ext_pushButton_3")
        self.ext_pushButton_4 = QtWidgets.QPushButton(self.tab_ext)
        self.ext_pushButton_4.setGeometry(QtCore.QRect(778,410,91,28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ext_pushButton_4.setFont(font)
        self.ext_pushButton_4.setObjectName("ext_pushButton_4")
        self.ext_pushButton_5 = QtWidgets.QPushButton(self.tab_ext)
        self.ext_pushButton_5.setGeometry(QtCore.QRect(530,670,121,71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ext_pushButton_5.setFont(font)
        self.ext_pushButton_5.setObjectName("ext_pushButton_5")
        self.ext_line = QtWidgets.QFrame(self.tab_ext)
        self.ext_line.setGeometry(QtCore.QRect(690,530,581,21))
        self.ext_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.ext_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ext_line.setObjectName("ext_line")
        self.ext_line_2 = QtWidgets.QFrame(self.tab_ext)
        self.ext_line_2.setGeometry(QtCore.QRect(680,50,20,721))
        self.ext_line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.ext_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ext_line_2.setObjectName("ext_line_2")
        self.ext_tableWidget_2 = QtWidgets.QTableWidget(self.tab_ext)
        self.ext_tableWidget_2.setGeometry(QtCore.QRect(700,590,571,151))
        self.ext_tableWidget_2.setObjectName("ext_tableWidget_2")
        self.ext_tableWidget_2.setColumnCount(0)
        self.ext_tableWidget_2.setRowCount(0)
        self.ext_line_6 = QtWidgets.QFrame(self.tab_ext)
        self.ext_line_6.setGeometry(QtCore.QRect(0,42,1271,16))
        self.ext_line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.ext_line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ext_line_6.setObjectName("ext_line_6")
        self.ext_pushButton_12 = QtWidgets.QPushButton(self.tab_ext)
        self.ext_pushButton_12.setGeometry(QtCore.QRect(239,0,111,50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ext_pushButton_12.setFont(font)
        self.ext_pushButton_12.setObjectName("ext_pushButton_12")
        self.ext_pushButton_13 = QtWidgets.QPushButton(self.tab_ext)
        self.ext_pushButton_13.setGeometry(QtCore.QRect(-1,0,111,50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ext_pushButton_13.setFont(font)
        self.ext_pushButton_13.setObjectName("ext_pushButton_13")
        self.ext_pushButton_14 = QtWidgets.QPushButton(self.tab_ext)
        self.ext_pushButton_14.setGeometry(QtCore.QRect(119,1,111,50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ext_pushButton_14.setFont(font)
        self.ext_pushButton_14.setObjectName("ext_pushButton_14")
        self.tabWidget.addTab(self.tab_ext,"영상검출")

        ######################## 오토포커싱 tab
        self.tab_afc = QtWidgets.QWidget()
        self.tab_afc.setObjectName("tab_afc")
        self.afc_frame_2 = QtWidgets.QFrame(self.tab_afc)
        self.afc_frame_2.setGeometry(QtCore.QRect(40,110,581,451))
        self.afc_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.afc_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.afc_frame_2.setObjectName("afc_frame_2")
        self.afc_label_14 = QtWidgets.QLabel(self.afc_frame_2)
        self.afc_label_14.setGeometry(QtCore.QRect(90,180,401,111))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.afc_label_14.setFont(font)
        self.afc_label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.afc_label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.afc_label_14.setObjectName("afc_label_14")
        self.afc_frame_3 = QtWidgets.QFrame(self.tab_afc)
        self.afc_frame_3.setGeometry(QtCore.QRect(730,110,511,451))
        self.afc_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.afc_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.afc_frame_3.setObjectName("afc_frame_3")
        self.afc_afc_label = QtWidgets.QLabel(self.afc_frame_3)
        self.afc_afc_label.setGeometry(QtCore.QRect(80,200,391,111))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.afc_afc_label.setFont(font)
        self.afc_afc_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.afc_afc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.afc_afc_label.setObjectName("afc_afc_label")
        self.afc_line_3 = QtWidgets.QFrame(self.tab_afc)
        self.afc_line_3.setGeometry(QtCore.QRect(666,60,20,711))
        self.afc_line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.afc_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.afc_line_3.setObjectName("afc_line_3")
        self.afc_label_16 = QtWidgets.QLabel(self.tab_afc)
        self.afc_label_16.setGeometry(QtCore.QRect(680,590,181,31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.afc_label_16.setFont(font)
        self.afc_label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.afc_label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.afc_label_16.setObjectName("afc_label_16")
        self.afc_line_4 = QtWidgets.QFrame(self.tab_afc)
        self.afc_line_4.setGeometry(QtCore.QRect(680,560,591,31))
        self.afc_line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.afc_line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.afc_line_4.setObjectName("afc_line_4")
        self.afc_tableView = QtWidgets.QTableView(self.tab_afc)
        self.afc_tableView.setGeometry(QtCore.QRect(700,620,551,131))
        self.afc_tableView.setObjectName("afc_tableView")
        self.afc_pushButton_8 = QtWidgets.QPushButton(self.tab_afc)
        self.afc_pushButton_8.setGeometry(QtCore.QRect(530,620,121,131))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.afc_pushButton_8.setFont(font)
        self.afc_pushButton_8.setObjectName("afc_pushButton_8")
        self.afc_line_5 = QtWidgets.QFrame(self.tab_afc)
        self.afc_line_5.setGeometry(QtCore.QRect(0,50,1271,16))
        self.afc_line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.afc_line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.afc_line_5.setObjectName("afc_line_5")
        self.afc_label_17 = QtWidgets.QLabel(self.tab_afc)
        self.afc_label_17.setGeometry(QtCore.QRect(0,70,181,31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.afc_label_17.setFont(font)
        self.afc_label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.afc_label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.afc_label_17.setObjectName("afc_label_17")
        self.afc_label_18 = QtWidgets.QLabel(self.tab_afc)
        self.afc_label_18.setGeometry(QtCore.QRect(690,70,181,31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.afc_label_18.setFont(font)
        self.afc_label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.afc_label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.afc_label_18.setObjectName("afc_label_18")
        self.afc_pushButton_9 = QtWidgets.QPushButton(self.tab_afc)
        self.afc_pushButton_9.setGeometry(QtCore.QRect(0,3,111,50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.afc_pushButton_9.setFont(font)
        self.afc_pushButton_9.setObjectName("afc_pushButton_9")
        self.afc_pushButton_10 = QtWidgets.QPushButton(self.tab_afc)
        self.afc_pushButton_10.setGeometry(QtCore.QRect(120,4,111,50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.afc_pushButton_10.setFont(font)
        self.afc_pushButton_10.setObjectName("afc_pushButton_10")
        self.afc_pushButton_11 = QtWidgets.QPushButton(self.tab_afc)
        self.afc_pushButton_11.setGeometry(QtCore.QRect(240,3,111,50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.afc_pushButton_11.setFont(font)
        self.afc_pushButton_11.setObjectName("afc_pushButton_11")
        self.tabWidget.addTab(self.tab_afc,"오토포커싱")

        ########################## 설정 tab
        self.tab_opt = QtWidgets.QWidget()
        self.tab_opt.setObjectName("tab_opt")
        self.opt_groupBox = QtWidgets.QGroupBox(self.tab_opt)
        self.opt_groupBox.setGeometry(QtCore.QRect(60,40,1161,171))
        self.opt_groupBox.setObjectName("opt_groupBox")
        self.opt_groupBox_2 = QtWidgets.QGroupBox(self.opt_groupBox)
        self.opt_groupBox_2.setGeometry(QtCore.QRect(250,170,1161,171))
        self.opt_groupBox_2.setObjectName("opt_groupBox_2")
        self.opt_label_4 = QtWidgets.QLabel(self.opt_groupBox)
        self.opt_label_4.setGeometry(QtCore.QRect(10,60,211,21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_4.setFont(font)
        self.opt_label_4.setScaledContents(False)
        self.opt_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_4.setWordWrap(True)
        self.opt_label_4.setObjectName("opt_label_4")
        self.opt_label_5 = QtWidgets.QLabel(self.opt_groupBox)
        self.opt_label_5.setGeometry(QtCore.QRect(10,120,211,21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_5.setFont(font)
        self.opt_label_5.setScaledContents(False)
        self.opt_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_5.setWordWrap(True)
        self.opt_label_5.setObjectName("opt_label_5")
        self.opt_label_6 = QtWidgets.QLabel(self.opt_groupBox)
        self.opt_label_6.setGeometry(QtCore.QRect(460,60,211,21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_6.setFont(font)
        self.opt_label_6.setScaledContents(False)
        self.opt_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_6.setWordWrap(True)
        self.opt_label_6.setObjectName("opt_label_6")
        self.opt_label_7 = QtWidgets.QLabel(self.opt_groupBox)
        self.opt_label_7.setGeometry(QtCore.QRect(460,120,211,21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_7.setFont(font)
        self.opt_label_7.setScaledContents(False)
        self.opt_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_7.setWordWrap(True)
        self.opt_label_7.setObjectName("opt_label_7")
        self.opt_label_8 = QtWidgets.QLabel(self.opt_groupBox)
        self.opt_label_8.setGeometry(QtCore.QRect(800,122,211,21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_8.setFont(font)
        self.opt_label_8.setScaledContents(False)
        self.opt_label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_8.setWordWrap(True)
        self.opt_label_8.setObjectName("opt_label_8")
        self.opt_lineEdit = QtWidgets.QLineEdit(self.opt_groupBox)
        self.opt_lineEdit.setGeometry(QtCore.QRect(220,60,151,20))
        self.opt_lineEdit.setObjectName("opt_lineEdit")
        self.opt_pushButton_6 = QtWidgets.QPushButton(self.opt_groupBox)
        self.opt_pushButton_6.setGeometry(QtCore.QRect(375,59,93,21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_pushButton_6.setFont(font)
        self.opt_pushButton_6.setObjectName("opt_pushButton_6")
        self.opt_pushButton_7 = QtWidgets.QPushButton(self.opt_groupBox)
        self.opt_pushButton_7.setGeometry(QtCore.QRect(805,59,93,21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_pushButton_7.setFont(font)
        self.opt_pushButton_7.setObjectName("opt_pushButton_7")
        self.opt_lineEdit_2 = QtWidgets.QLineEdit(self.opt_groupBox)
        self.opt_lineEdit_2.setGeometry(QtCore.QRect(650,60,151,20))
        self.opt_lineEdit_2.setObjectName("opt_lineEdit_2")
        self.opt_comboBox = QtWidgets.QComboBox(self.opt_groupBox)
        self.opt_comboBox.setGeometry(QtCore.QRect(220,120,151,22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_comboBox.setFont(font)
        self.opt_comboBox.setEditable(False)
        self.opt_comboBox.setCurrentText("확장자 선택")
        self.opt_comboBox.setModelColumn(0)
        self.opt_comboBox.setObjectName("opt_comboBox")
        self.opt_comboBox.addItem("")
        self.opt_comboBox.addItem("")
        self.opt_comboBox_2 = QtWidgets.QComboBox(self.opt_groupBox)
        self.opt_comboBox_2.setGeometry(QtCore.QRect(650,120,151,22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_comboBox_2.setFont(font)
        self.opt_comboBox_2.setCurrentText("화질 선택")
        self.opt_comboBox_2.setObjectName("opt_comboBox_2")
        self.opt_comboBox_2.addItem("")
        self.opt_comboBox_3 = QtWidgets.QComboBox(self.opt_groupBox)
        self.opt_comboBox_3.setGeometry(QtCore.QRect(997,121,151,22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_comboBox_3.setFont(font)
        self.opt_comboBox_3.setCurrentText("확장자 선택")
        self.opt_comboBox_3.setObjectName("opt_comboBox_3")
        self.opt_comboBox_3.addItem("")
        self.opt_groupBox_3 = QtWidgets.QGroupBox(self.tab_opt)
        self.opt_groupBox_3.setGeometry(QtCore.QRect(60,270,1161,171))
        self.opt_groupBox_3.setObjectName("opt_groupBox_3")
        self.opt_groupBox_4 = QtWidgets.QGroupBox(self.opt_groupBox_3)
        self.opt_groupBox_4.setGeometry(QtCore.QRect(250,170,1161,171))
        self.opt_groupBox_4.setObjectName("opt_groupBox_4")
        self.opt_label_9 = QtWidgets.QLabel(self.opt_groupBox_3)
        self.opt_label_9.setGeometry(QtCore.QRect(0,60,211,21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_9.setFont(font)
        self.opt_label_9.setScaledContents(False)
        self.opt_label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_9.setWordWrap(True)
        self.opt_label_9.setObjectName("opt_label_9")
        self.opt_comboBox_4 = QtWidgets.QComboBox(self.opt_groupBox_3)
        self.opt_comboBox_4.setGeometry(QtCore.QRect(210,60,151,22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_comboBox_4.setFont(font)
        self.opt_comboBox_4.setCurrentText("5초")
        self.opt_comboBox_4.setObjectName("opt_comboBox_4")
        self.opt_comboBox_4.addItem("")
        self.opt_comboBox_4.addItem("")
        self.opt_comboBox_4.addItem("")
        self.opt_comboBox_4.addItem("")
        self.opt_label_10 = QtWidgets.QLabel(self.opt_groupBox_3)
        self.opt_label_10.setGeometry(QtCore.QRect(30,90,891,21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.opt_label_10.setFont(font)
        self.opt_label_10.setScaledContents(False)
        self.opt_label_10.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.opt_label_10.setWordWrap(True)
        self.opt_label_10.setObjectName("opt_label_10")
        self.opt_groupBox_5 = QtWidgets.QGroupBox(self.tab_opt)
        self.opt_groupBox_5.setGeometry(QtCore.QRect(60,500,1161,171))
        self.opt_groupBox_5.setObjectName("opt_groupBox_5")
        self.opt_groupBox_6 = QtWidgets.QGroupBox(self.opt_groupBox_5)
        self.opt_groupBox_6.setGeometry(QtCore.QRect(250,170,1161,171))
        self.opt_groupBox_6.setObjectName("opt_groupBox_6")
        self.opt_label_11 = QtWidgets.QLabel(self.opt_groupBox_5)
        self.opt_label_11.setGeometry(QtCore.QRect(50,80,211,21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_11.setFont(font)
        self.opt_label_11.setScaledContents(False)
        self.opt_label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_11.setWordWrap(True)
        self.opt_label_11.setObjectName("opt_label_11")
        self.opt_label_12 = QtWidgets.QLabel(self.opt_groupBox_5)
        self.opt_label_12.setGeometry(QtCore.QRect(50,40,211,21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_12.setFont(font)
        self.opt_label_12.setScaledContents(False)
        self.opt_label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_12.setWordWrap(True)
        self.opt_label_12.setObjectName("opt_label_12")
        self.opt_spinBox = QtWidgets.QSpinBox(self.opt_groupBox_5)
        self.opt_spinBox.setGeometry(QtCore.QRect(260,80,81,22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_spinBox.setFont(font)
        self.opt_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_spinBox.setMaximum(2000)
        self.opt_spinBox.setProperty("value",300)
        self.opt_spinBox.setObjectName("opt_spinBox")
        self.opt_spinBox_2 = QtWidgets.QSpinBox(self.opt_groupBox_5)
        self.opt_spinBox_2.setGeometry(QtCore.QRect(260,40,81,22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_spinBox_2.setFont(font)
        self.opt_spinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_spinBox_2.setMaximum(2000)
        self.opt_spinBox_2.setProperty("value",600)
        self.opt_spinBox_2.setObjectName("opt_spinBox_2")
        self.opt_label_13 = QtWidgets.QLabel(self.opt_groupBox_5)
        self.opt_label_13.setGeometry(QtCore.QRect(90,120,891,21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.opt_label_13.setFont(font)
        self.opt_label_13.setScaledContents(False)
        self.opt_label_13.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.opt_label_13.setWordWrap(True)
        self.opt_label_13.setObjectName("opt_label_13")
        self.tabWidget.addTab(self.tab_opt,"설정")

        # class 선언
        self.opt = option(self)
        self.cm = common.common()
        self.ext = extract.extract(self)

        # connect signal to slot
        self.opt_pushButton_6.clicked.connect(self.select_directory_clicked)
        self.opt_pushButton_7.clicked.connect(self.select_directory_clicked)
        self.ext_pushButton_5.clicked.connect(self.start_extractor)
        self.afc_pushButton_8.clicked.connect(self.start_autofocus)
        self.ext_pushButton_4.clicked.connect(self.deleted_current_select)
        # self.pushButton_13.clicked.connect(self.clicked_local_upload)
        # self.pushButton_9.clicked.connect(self.clicked_local_upload)

        self.action = QtWidgets.QAction(Form)
        self.action.setObjectName("action")
        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        self.opt_comboBox_4.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def deleted_current_select(self):
        self.ext.add_list()

    def select_directory_clicked(self):
        button = self.sender()
        self.opt.set_directory(button)

    def start_autofocus(self):
        height, width = self.opt.get_coord()
        print("height : {}".format(height))
        print("width : {}".format(width))


    def start_extractor(self):
        print("setting second : {}".format(self.opt.get_buffertime()))


    def clicked_local_upload(self):
        pass
        # form = second_form()
        # form.exec_()
        # data = form.getData()



    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Human?", None, -1))
        self.ext_tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Form", "썸네일", None, -1))
        self.ext_tableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Form", "검출구간", None, -1))
        self.ext_tableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Form", "검출구간수정", None, -1))
        self.ext_tableWidget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Form", "라벨명", None, -1))
        self.ext_tableWidget.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Form", "기타정보", None, -1))
        self.ext_tableWidget.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("Form", "선택", None, -1))
        __sortingEnabled = self.ext_tableWidget.isSortingEnabled()
        self.ext_tableWidget.setSortingEnabled(False)
        self.ext_tableWidget.item(0, 0).setText(QtWidgets.QApplication.translate("Form", "썸네일 이미지 추가예정", None, -1))
        self.ext_tableWidget.item(0, 1).setText(QtWidgets.QApplication.translate("Form", "00:22-00:27", None, -1))
        self.ext_tableWidget.item(0, 2).setText(QtWidgets.QApplication.translate("Form", "셀렉트바 추가", None, -1))
        self.ext_tableWidget.item(0, 3).setText(QtWidgets.QApplication.translate("Form", "아이린", None, -1))
        self.ext_tableWidget.item(0, 4).setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.ext_tableWidget.item(0, 5).setText(QtWidgets.QApplication.translate("Form", "체크박스 추가", None, -1))
        self.ext_tableWidget.item(1, 0).setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.ext_tableWidget.item(1, 1).setText(QtWidgets.QApplication.translate("Form", "00:35-00:40", None, -1))
        self.ext_tableWidget.item(1, 2).setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.ext_tableWidget.item(1, 3).setText(QtWidgets.QApplication.translate("Form", "아이린", None, -1))
        self.ext_tableWidget.item(1, 4).setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.ext_tableWidget.item(1, 5).setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.ext_tableWidget.item(2, 0).setText(QtWidgets.QApplication.translate("Form", "2", None, -1))
        self.ext_tableWidget.item(2, 1).setText(QtWidgets.QApplication.translate("Form", "00:50-00:55", None, -1))
        self.ext_tableWidget.item(2, 2).setText(QtWidgets.QApplication.translate("Form", "2", None, -1))
        self.ext_tableWidget.item(2, 3).setText(QtWidgets.QApplication.translate("Form", "아이린", None, -1))
        self.ext_tableWidget.item(2, 4).setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.ext_tableWidget.item(2, 5).setText(QtWidgets.QApplication.translate("Form", "2", None, -1))
        self.ext_tableWidget.item(3, 0).setText(QtWidgets.QApplication.translate("Form", "3", None, -1))
        self.ext_tableWidget.item(3, 1).setText(QtWidgets.QApplication.translate("Form", "01:13-01:18", None, -1))
        self.ext_tableWidget.item(3, 2).setText(QtWidgets.QApplication.translate("Form", "3", None, -1))
        self.ext_tableWidget.item(3, 3).setText(QtWidgets.QApplication.translate("Form", "아이린", None, -1))
        self.ext_tableWidget.item(3, 4).setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.ext_tableWidget.item(3, 5).setText(QtWidgets.QApplication.translate("Form", "3", None, -1))
        self.ext_tableWidget.setSortingEnabled(__sortingEnabled)
        self.ext_label.setText(QtWidgets.QApplication.translate("Form", "Video Area", None, -1))
        self.ext_label_2.setText(QtWidgets.QApplication.translate("Form", "검출 내역", None, -1))
        self.ext_label_3.setText(QtWidgets.QApplication.translate("Form", "검출 대상 리스트", None, -1))
        self.ext_pushButton.setText(QtWidgets.QApplication.translate("Form", "초기화", None, -1))
        self.ext_pushButton_2.setText(QtWidgets.QApplication.translate("Form", "선택 내려받기", None, -1))
        self.ext_pushButton_3.setText(QtWidgets.QApplication.translate("Form", "전체 내려받기", None, -1))
        self.ext_pushButton_4.setText(QtWidgets.QApplication.translate("Form", "선택 삭제", None, -1))
        self.ext_pushButton_5.setText(QtWidgets.QApplication.translate("Form", "검출 시작", None, -1))
        self.ext_pushButton_12.setText(QtWidgets.QApplication.translate("Form", "영상 내려받기", None, -1))
        self.ext_pushButton_13.setText(QtWidgets.QApplication.translate("Form", "로컬 업로드", None, -1))
        self.ext_pushButton_14.setText(QtWidgets.QApplication.translate("Form", "URL 업로드", None, -1))
        self.afc_label_14.setText(QtWidgets.QApplication.translate("Form", "Original Video Area", None, -1))
        self.afc_afc_label.setText(QtWidgets.QApplication.translate("Form", "Focus Video Area", None, -1))
        self.afc_label_16.setText(QtWidgets.QApplication.translate("Form", "검출 대상 리스트", None, -1))
        self.afc_pushButton_8.setText(QtWidgets.QApplication.translate("Form", "검출 시작", None, -1))
        self.afc_label_17.setText(QtWidgets.QApplication.translate("Form", "원본 영상", None, -1))
        self.afc_label_18.setText(QtWidgets.QApplication.translate("Form", "포커싱 영상", None, -1))
        self.afc_pushButton_9.setText(QtWidgets.QApplication.translate("Form", "로컬 업로드", None, -1))
        self.afc_pushButton_10.setText(QtWidgets.QApplication.translate("Form", "URL 업로드", None, -1))
        self.afc_pushButton_11.setText(QtWidgets.QApplication.translate("Form", "영상 내려받기", None, -1))
        self.opt_groupBox.setTitle(QtWidgets.QApplication.translate("Form", "공통 옵션 설정", None, -1))
        self.opt_groupBox_2.setTitle(QtWidgets.QApplication.translate("Form", "GroupBox", None, -1))
        self.opt_label_4.setText(QtWidgets.QApplication.translate("Form", "URL 업로드 파일 경로", None, -1))
        self.opt_label_5.setText(QtWidgets.QApplication.translate("Form", "내려받기 확장자", None, -1))
        self.opt_label_6.setText(QtWidgets.QApplication.translate("Form", "내려받기 저장 경로", None, -1))
        self.opt_label_7.setText(QtWidgets.QApplication.translate("Form", "내려받기 화질 선택", None, -1))
        self.opt_label_8.setText(QtWidgets.QApplication.translate("Form", "좌표파일 확장자 선택", None, -1))
        self.opt_pushButton_6.setText(QtWidgets.QApplication.translate("Form", "폴더찾기", None, -1))
        self.opt_pushButton_7.setText(QtWidgets.QApplication.translate("Form", "폴더찾기", None, -1))
        self.opt_comboBox.setItemText(24, QtWidgets.QApplication.translate("Form", "확장자 선택", None, -1))
        self.opt_comboBox.setItemText(25, QtWidgets.QApplication.translate("Form", "mp4", None, -1))
        self.opt_comboBox_2.setItemText(26, QtWidgets.QApplication.translate("Form", "화질 선택", None, -1))
        self.opt_comboBox_3.setItemText(27, QtWidgets.QApplication.translate("Form", "확장자 선택", None, -1))
        self.opt_groupBox_3.setTitle(QtWidgets.QApplication.translate("Form", "영상 검출 옵션 설정", None, -1))
        self.opt_groupBox_4.setTitle(QtWidgets.QApplication.translate("Form", "GroupBox", None, -1))
        self.opt_label_9.setText(QtWidgets.QApplication.translate("Form", "추출 영상 버퍼 시간", None, -1))
        self.opt_comboBox_4.setItemText(28, QtWidgets.QApplication.translate("Form", "버퍼(초)선택", None, -1))
        self.opt_comboBox_4.setItemText(29, QtWidgets.QApplication.translate("Form", "1초", None, -1))
        self.opt_comboBox_4.setItemText(30, QtWidgets.QApplication.translate("Form", "3초", None, -1))
        self.opt_comboBox_4.setItemText(31, QtWidgets.QApplication.translate("Form", "5초", None, -1))
        self.opt_label_10.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" color:#ff0000;\">※ 검출 내역 한 건당 설정 할 수 있는 버퍼의 범위는 00:01 ~ 00:10 초 사이에서 설정 할 수 있습니다.</span></p></body></html>", None, -1))
        self.opt_groupBox_5.setTitle(QtWidgets.QApplication.translate("Form", "오토 포커싱 옵션 설정", None, -1))
        self.opt_groupBox_6.setTitle(QtWidgets.QApplication.translate("Form", "GroupBox", None, -1))
        self.opt_label_11.setText(QtWidgets.QApplication.translate("Form", "포커싱 박스 넓이", None, -1))
        self.opt_label_12.setText(QtWidgets.QApplication.translate("Form", "포커싱 박스 높이", None, -1))
        self.opt_label_13.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" color:#ff0000;\">※ 포커싱 박스의 넓이 및 높이는 대상 영상의 해상도 보다 클 수 없습니다.</span></p></body></html>", None, -1))
        self.action.setText(QtWidgets.QApplication.translate("Form", "테스트", None, -1))
        self.action.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>툴팁화면</p></body></html>", None, -1))

class second_form(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super(second_form, self).__init__(parent)
        self.setWindowTitle("로컬 업로드")

        self.label = QtWidgets.QLabel("path")
        self.edit = QtWidgets.QLineEdit("Write file path")

        layout = QtWidgets.QVBoxLayout()
        layout.addWidget(self.edit)

        self.setLayout(layout)

    def getData(self):
        return self.edit.text()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
