# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui',
# licensing of 'mainWindow.ui' applies.
#
# Created: Mon Aug 26 10:55:48 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
		########
		#	Main Form Default
		#	- 메인 폼
		########
        Form.setObjectName("Form")
        Form.resize(1280, 800)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainTabWidget = QtWidgets.QTabWidget(Form)
        self.mainTabWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("나눔고딕코딩")
        font.setPointSize(14)
		
		########
		#	Main tab Default
		#	- 탭 전체 공통 옵션
		########
        self.mainTabWidget.setFont(font)
        self.mainTabWidget.setObjectName("mainTabWidget")
		
		########
		#	extTab Default
		#	- 영상검출탭
		########
        self.tab_ext = QtWidgets.QWidget()
        self.tab_ext.setEnabled(True)
        self.tab_ext.setObjectName("tab_ext")
        self.ext_tableWidget_extResultList = QtWidgets.QTableWidget(self.tab_ext)
        self.ext_tableWidget_extResultList.setGeometry(QtCore.QRect(700, 100, 541, 291))
        self.ext_tableWidget_extResultList.setObjectName("ext_tableWidget_extResultList")
        self.ext_tableWidget_extResultList.setColumnCount(6)
        self.ext_tableWidget_extResultList.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(3, 5, item)
        self.ext_frame_extMd = QtWidgets.QFrame(self.tab_ext)
        self.ext_frame_extMd.setGeometry(QtCore.QRect(0, 80, 671, 441))
        self.ext_frame_extMd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ext_frame_extMd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ext_frame_extMd.setObjectName("ext_frame_extMd")
        self.ext_label_extMd = QtWidgets.QLabel(self.ext_frame_extMd)
        self.ext_label_extMd.setGeometry(QtCore.QRect(0, 0, 671, 441))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.ext_label_extMd.setFont(font)
        self.ext_label_extMd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ext_label_extMd.setAlignment(QtCore.Qt.AlignCenter)
        self.ext_label_extMd.setObjectName("ext_label_extMd")
        self.ext_label_extResultList = QtWidgets.QLabel(self.tab_ext)
        self.ext_label_extResultList.setGeometry(QtCore.QRect(700, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.ext_label_extResultList.setFont(font)
        self.ext_label_extResultList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ext_label_extResultList.setAlignment(QtCore.Qt.AlignCenter)
        self.ext_label_extResultList.setObjectName("ext_label_extResultList")
        self.ext_label_classList = QtWidgets.QLabel(self.tab_ext)
        self.ext_label_classList.setGeometry(QtCore.QRect(700, 550, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.ext_label_classList.setFont(font)
        self.ext_label_classList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ext_label_classList.setAlignment(QtCore.Qt.AlignCenter)
        self.ext_label_classList.setObjectName("ext_label_classList")
        self.ext_pushButton_startExt = QtWidgets.QPushButton(self.tab_ext)
        self.ext_pushButton_startExt.setGeometry(QtCore.QRect(530, 670, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ext_pushButton_startExt.setFont(font)
        self.ext_pushButton_startExt.setObjectName("ext_pushButton_startExt")
        self.ext_line_rMid = QtWidgets.QFrame(self.tab_ext)
        self.ext_line_rMid.setGeometry(QtCore.QRect(690, 530, 581, 21))
        self.ext_line_rMid.setFrameShape(QtWidgets.QFrame.HLine)
        self.ext_line_rMid.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ext_line_rMid.setObjectName("ext_line_rMid")
        self.ext_line_mid = QtWidgets.QFrame(self.tab_ext)
        self.ext_line_mid.setGeometry(QtCore.QRect(680, 50, 20, 721))
        self.ext_line_mid.setFrameShape(QtWidgets.QFrame.VLine)
        self.ext_line_mid.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ext_line_mid.setObjectName("ext_line_mid")
        self.ext_tableWidget_classList = QtWidgets.QTableWidget(self.tab_ext)
        self.ext_tableWidget_classList.setGeometry(QtCore.QRect(700, 590, 541, 151))
        self.ext_tableWidget_classList.setObjectName("ext_tableWidget_classList")
        self.ext_tableWidget_classList.setColumnCount(0)
        self.ext_tableWidget_classList.setRowCount(0)
        self.ext_line_top = QtWidgets.QFrame(self.tab_ext)
        self.ext_line_top.setGeometry(QtCore.QRect(0, 50, 1271, 16))
        self.ext_line_top.setFrameShape(QtWidgets.QFrame.HLine)
        self.ext_line_top.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ext_line_top.setObjectName("ext_line_top")
        self.widget = QtWidgets.QWidget(self.tab_ext)
        self.widget.setGeometry(QtCore.QRect(698, 410, 541, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ext_pushButton_allClear = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ext_pushButton_allClear.setFont(font)
        self.ext_pushButton_allClear.setObjectName("ext_pushButton_allClear")
        self.horizontalLayout.addWidget(self.ext_pushButton_allClear)
        self.ext_pushButton_selectDelete = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ext_pushButton_selectDelete.setFont(font)
        self.ext_pushButton_selectDelete.setObjectName("ext_pushButton_selectDelete")
        self.horizontalLayout.addWidget(self.ext_pushButton_selectDelete)
        self.ext_pushButton_allSave = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ext_pushButton_allSave.setFont(font)
        self.ext_pushButton_allSave.setObjectName("ext_pushButton_allSave")
        self.horizontalLayout.addWidget(self.ext_pushButton_allSave)
        self.ext_pushButton_selectSave = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ext_pushButton_selectSave.setFont(font)
        self.ext_pushButton_selectSave.setObjectName("ext_pushButton_selectSave")
        self.horizontalLayout.addWidget(self.ext_pushButton_selectSave)
        self.splitter = QtWidgets.QSplitter(self.tab_ext)
        self.splitter.setGeometry(QtCore.QRect(0, 3, 331, 51))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.ext_pushButton_localUpload = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ext_pushButton_localUpload.setFont(font)
        self.ext_pushButton_localUpload.setObjectName("ext_pushButton_localUpload")
        self.ext_pushButton_urlUpload = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ext_pushButton_urlUpload.setFont(font)
        self.ext_pushButton_urlUpload.setObjectName("ext_pushButton_urlUpload")
        self.ext_pushButton_mdDown = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ext_pushButton_mdDown.setFont(font)
        self.ext_pushButton_mdDown.setObjectName("ext_pushButton_mdDown")
        #self.mainTabWidget.addTab(self.tab_ext, "영상검출")
		
		
		
		########
		#	afcTab Default
		#	- 오토포커싱탭
		########
        self.tab_afc = QtWidgets.QWidget()
        self.tab_afc.setObjectName("tab_afc")
        self.afc_frame_2_beforeMd = QtWidgets.QFrame(self.tab_afc)
        self.afc_frame_2_beforeMd.setGeometry(QtCore.QRect(40, 110, 581, 451))
        self.afc_frame_2_beforeMd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.afc_frame_2_beforeMd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.afc_frame_2_beforeMd.setObjectName("afc_frame_2_beforeMd")
        self.afc_label_14_beforeMd = QtWidgets.QLabel(self.afc_frame_2_beforeMd)
        self.afc_label_14_beforeMd.setGeometry(QtCore.QRect(0, 0, 581, 451))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.afc_label_14_beforeMd.setFont(font)
        self.afc_label_14_beforeMd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.afc_label_14_beforeMd.setAlignment(QtCore.Qt.AlignCenter)
        self.afc_label_14_beforeMd.setObjectName("afc_label_14_beforeMd")
        self.afc_frame_3_afterMd = QtWidgets.QFrame(self.tab_afc)
        self.afc_frame_3_afterMd.setGeometry(QtCore.QRect(710, 100, 511, 451))
        self.afc_frame_3_afterMd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.afc_frame_3_afterMd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.afc_frame_3_afterMd.setObjectName("afc_frame_3_afterMd")
        self.afc_afc_label_afterMd = QtWidgets.QLabel(self.afc_frame_3_afterMd)
        self.afc_afc_label_afterMd.setGeometry(QtCore.QRect(0, 0, 511, 451))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.afc_afc_label_afterMd.setFont(font)
        self.afc_afc_label_afterMd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.afc_afc_label_afterMd.setAlignment(QtCore.Qt.AlignCenter)
        self.afc_afc_label_afterMd.setObjectName("afc_afc_label_afterMd")
        self.afc_line_mid = QtWidgets.QFrame(self.tab_afc)
        self.afc_line_mid.setGeometry(QtCore.QRect(666, 60, 20, 711))
        self.afc_line_mid.setFrameShape(QtWidgets.QFrame.VLine)
        self.afc_line_mid.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.afc_line_mid.setObjectName("afc_line_mid")
        self.afc_label_classList = QtWidgets.QLabel(self.tab_afc)
        self.afc_label_classList.setGeometry(QtCore.QRect(690, 590, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.afc_label_classList.setFont(font)
        self.afc_label_classList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.afc_label_classList.setAlignment(QtCore.Qt.AlignCenter)
        self.afc_label_classList.setObjectName("afc_label_classList")
        self.afc_line_rMid = QtWidgets.QFrame(self.tab_afc)
        self.afc_line_rMid.setGeometry(QtCore.QRect(680, 560, 591, 31))
        self.afc_line_rMid.setFrameShape(QtWidgets.QFrame.HLine)
        self.afc_line_rMid.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.afc_line_rMid.setObjectName("afc_line_rMid")
        self.afc_pushButton_startExt = QtWidgets.QPushButton(self.tab_afc)
        self.afc_pushButton_startExt.setGeometry(QtCore.QRect(530, 620, 121, 131))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.afc_pushButton_startExt.setFont(font)
        self.afc_pushButton_startExt.setObjectName("afc_pushButton_startExt")
        self.afc_line_top = QtWidgets.QFrame(self.tab_afc)
        self.afc_line_top.setGeometry(QtCore.QRect(0, 50, 1271, 16))
        self.afc_line_top.setFrameShape(QtWidgets.QFrame.HLine)
        self.afc_line_top.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.afc_line_top.setObjectName("afc_line_top")
        self.afc_label_beforeMd = QtWidgets.QLabel(self.tab_afc)
        self.afc_label_beforeMd.setGeometry(QtCore.QRect(0, 70, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.afc_label_beforeMd.setFont(font)
        self.afc_label_beforeMd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.afc_label_beforeMd.setAlignment(QtCore.Qt.AlignCenter)
        self.afc_label_beforeMd.setObjectName("afc_label_beforeMd")
        self.afc_label_afterMd = QtWidgets.QLabel(self.tab_afc)
        self.afc_label_afterMd.setGeometry(QtCore.QRect(670, 70, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.afc_label_afterMd.setFont(font)
        self.afc_label_afterMd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.afc_label_afterMd.setAlignment(QtCore.Qt.AlignCenter)
        self.afc_label_afterMd.setObjectName("afc_label_afterMd")
        self.afc_scrollArea_classList = QtWidgets.QScrollArea(self.tab_afc)
        self.afc_scrollArea_classList.setGeometry(QtCore.QRect(710, 620, 511, 131))
        self.afc_scrollArea_classList.setWidgetResizable(True)
        self.afc_scrollArea_classList.setObjectName("afc_scrollArea_classList")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 509, 129))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.afc_scrollArea_classList.setWidget(self.scrollAreaWidgetContents)
        self.splitter_2 = QtWidgets.QSplitter(self.tab_afc)
        self.splitter_2.setGeometry(QtCore.QRect(0, 3, 331, 51))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.afc_pushButton_localUpload = QtWidgets.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.afc_pushButton_localUpload.setFont(font)
        self.afc_pushButton_localUpload.setObjectName("afc_pushButton_localUpload")
        self.afc_pushButton_urlUpload = QtWidgets.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.afc_pushButton_urlUpload.setFont(font)
        self.afc_pushButton_urlUpload.setObjectName("afc_pushButton_urlUpload")
        self.afc_pushButton_mdDown = QtWidgets.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.afc_pushButton_mdDown.setFont(font)
        self.afc_pushButton_mdDown.setObjectName("afc_pushButton_mdDown")
        #self.mainTabWidget.addTab(self.tab_afc, "오토포커싱")
		
		########
		#	optTab Default
		#	- 옵션설정 탭
		########
        self.tab_opt = QtWidgets.QWidget()
        self.tab_opt.setObjectName("tab_opt")
		
		######## 설정.공통옵션설정 start
        self.opt_groupBox_top = QtWidgets.QGroupBox(self.tab_opt)
        self.opt_groupBox_top.setGeometry(QtCore.QRect(60, 40, 1161, 171))
        self.opt_groupBox_top.setObjectName("opt_groupBox_top")
        self.widget1 = QtWidgets.QWidget(self.opt_groupBox_top)
        self.widget1.setGeometry(QtCore.QRect(130, 110, 204, 22))
        self.widget1.setObjectName("widget1")
        self.opt_horizontalLayout3 = QtWidgets.QHBoxLayout(self.widget1)
        self.opt_horizontalLayout3.setContentsMargins(0, 0, 0, 0)
        self.opt_horizontalLayout3.setObjectName("opt_horizontalLayout3")
        self.opt_label_saveFmt = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_saveFmt.setFont(font)
        self.opt_label_saveFmt.setScaledContents(False)
        self.opt_label_saveFmt.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_saveFmt.setWordWrap(True)
        self.opt_label_saveFmt.setObjectName("opt_label_saveFmt")
        self.opt_horizontalLayout3.addWidget(self.opt_label_saveFmt)
        self.opt_comboBox_downFileFmt = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_comboBox_downFileFmt.setFont(font)
        self.opt_comboBox_downFileFmt.setEditable(False)
        self.opt_comboBox_downFileFmt.setCurrentText("확장자 선택")
        self.opt_comboBox_downFileFmt.setModelColumn(0)
        self.opt_comboBox_downFileFmt.setObjectName("opt_comboBox_downFileFmt")
        self.opt_comboBox_downFileFmt.addItem("")
        self.opt_comboBox_downFileFmt.addItem("")
        self.opt_horizontalLayout3.addWidget(self.opt_comboBox_downFileFmt)
        self.widget2 = QtWidgets.QWidget(self.opt_groupBox_top)
        self.widget2.setGeometry(QtCore.QRect(750, 110, 239, 22))
        self.widget2.setObjectName("widget2")
        self.opt_horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget2)
        self.opt_horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.opt_horizontalLayout_5.setObjectName("opt_horizontalLayout_5")
        self.opt_label_coordFmt = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_coordFmt.setFont(font)
        self.opt_label_coordFmt.setScaledContents(False)
        self.opt_label_coordFmt.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_coordFmt.setWordWrap(True)
        self.opt_label_coordFmt.setObjectName("opt_label_coordFmt")
        self.opt_horizontalLayout_5.addWidget(self.opt_label_coordFmt)
        self.opt_comboBox_coordFmt = QtWidgets.QComboBox(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_comboBox_coordFmt.setFont(font)
        self.opt_comboBox_coordFmt.setCurrentText("확장자 선택")
        self.opt_comboBox_coordFmt.setObjectName("opt_comboBox_coordFmt")
        self.opt_comboBox_coordFmt.addItem("")
        self.opt_horizontalLayout_5.addWidget(self.opt_comboBox_coordFmt)
        self.widget3 = QtWidgets.QWidget(self.opt_groupBox_top)
        self.widget3.setGeometry(QtCore.QRect(440, 110, 213, 22))
        self.widget3.setObjectName("widget3")
        self.opt_horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget3)
        self.opt_horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.opt_horizontalLayout_4.setObjectName("opt_horizontalLayout_4")
        self.opt_label_saveMdQual = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_saveMdQual.setFont(font)
        self.opt_label_saveMdQual.setScaledContents(False)
        self.opt_label_saveMdQual.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_saveMdQual.setWordWrap(True)
        self.opt_label_saveMdQual.setObjectName("opt_label_saveMdQual")
        self.opt_horizontalLayout_4.addWidget(self.opt_label_saveMdQual)
        self.opt_comboBox_downFileDef = QtWidgets.QComboBox(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_comboBox_downFileDef.setFont(font)
        self.opt_comboBox_downFileDef.setCurrentText("화질 선택")
        self.opt_comboBox_downFileDef.setObjectName("opt_comboBox_downFileDef")
        self.opt_comboBox_downFileDef.addItem("")
        self.opt_horizontalLayout_4.addWidget(self.opt_comboBox_downFileDef)
        self.widget4 = QtWidgets.QWidget(self.opt_groupBox_top)
        self.widget4.setGeometry(QtCore.QRect(100, 50, 413, 27))
        self.widget4.setObjectName("widget4")
        self.opt_horizontalLayout_1 = QtWidgets.QHBoxLayout(self.widget4)
        self.opt_horizontalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.opt_horizontalLayout_1.setObjectName("opt_horizontalLayout_1")
        self.opt_label_urlSaveDir = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_urlSaveDir.setFont(font)
        self.opt_label_urlSaveDir.setScaledContents(False)
        self.opt_label_urlSaveDir.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_urlSaveDir.setWordWrap(True)
        self.opt_label_urlSaveDir.setObjectName("opt_label_urlSaveDir")
        self.opt_horizontalLayout_1.addWidget(self.opt_label_urlSaveDir)
        self.opt_lineEdit_urlSaveDir = QtWidgets.QLineEdit(self.widget4)
        self.opt_lineEdit_urlSaveDir.setObjectName("opt_lineEdit_urlSaveDir")
        self.opt_horizontalLayout_1.addWidget(self.opt_lineEdit_urlSaveDir)
        self.opt_pushButton_urlDownDir = QtWidgets.QPushButton(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_pushButton_urlDownDir.setFont(font)
        self.opt_pushButton_urlDownDir.setObjectName("opt_pushButton_urlDownDir")
        self.opt_horizontalLayout_1.addWidget(self.opt_pushButton_urlDownDir)
        self.widget5 = QtWidgets.QWidget(self.opt_groupBox_top)
        self.widget5.setGeometry(QtCore.QRect(610, 50, 399, 27))
        self.widget5.setObjectName("widget5")
        self.opt_horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget5)
        self.opt_horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.opt_horizontalLayout_2.setObjectName("opt_horizontalLayout_2")
        self.opt_label_localSaveDir = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_localSaveDir.setFont(font)
        self.opt_label_localSaveDir.setScaledContents(False)
        self.opt_label_localSaveDir.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_localSaveDir.setWordWrap(True)
        self.opt_label_localSaveDir.setObjectName("opt_label_localSaveDir")
        self.opt_horizontalLayout_2.addWidget(self.opt_label_localSaveDir)
        self.opt_lineEdit_saveDir = QtWidgets.QLineEdit(self.widget5)
        self.opt_lineEdit_saveDir.setObjectName("opt_lineEdit_saveDir")
        self.opt_horizontalLayout_2.addWidget(self.opt_lineEdit_saveDir)
        self.opt_pushButton_saveDir = QtWidgets.QPushButton(self.widget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_pushButton_saveDir.setFont(font)
        self.opt_pushButton_saveDir.setObjectName("opt_pushButton_saveDir")
        self.opt_horizontalLayout_2.addWidget(self.opt_pushButton_saveDir)
		######## 설정.공통옵션설정 end
		
		######## 설정.영상 검출 옵션 설정 start
        self.opt_groupBox_mid = QtWidgets.QGroupBox(self.tab_opt)
        self.opt_groupBox_mid.setGeometry(QtCore.QRect(60, 270, 1161, 171))
        self.opt_groupBox_mid.setObjectName("opt_groupBox_mid")
        self.opt_groupBox_4 = QtWidgets.QGroupBox(self.opt_groupBox_mid)
        self.opt_groupBox_4.setGeometry(QtCore.QRect(250, 170, 1161, 171))
        self.opt_groupBox_4.setObjectName("opt_groupBox_4")
        self.opt_label_cn1 = QtWidgets.QLabel(self.opt_groupBox_mid)
        self.opt_label_cn1.setGeometry(QtCore.QRect(340, 54, 701, 75))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.opt_label_cn1.setFont(font)
        self.opt_label_cn1.setScaledContents(False)
        self.opt_label_cn1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.opt_label_cn1.setWordWrap(True)
        self.opt_label_cn1.setObjectName("opt_label_cn1")
        self.widget6 = QtWidgets.QWidget(self.opt_groupBox_mid)
        self.widget6.setGeometry(QtCore.QRect(50, 80, 238, 22))
        self.widget6.setObjectName("widget6")
        self.opt_horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget6)
        self.opt_horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.opt_horizontalLayout_6.setObjectName("opt_horizontalLayout_6")
        self.opt_label_extButTm = QtWidgets.QLabel(self.widget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_extButTm.setFont(font)
        self.opt_label_extButTm.setScaledContents(False)
        self.opt_label_extButTm.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_extButTm.setWordWrap(True)
        self.opt_label_extButTm.setObjectName("opt_label_extButTm")
        self.opt_horizontalLayout_6.addWidget(self.opt_label_extButTm)
        self.opt_comboBox_bufTime = QtWidgets.QComboBox(self.widget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_comboBox_bufTime.setFont(font)
        self.opt_comboBox_bufTime.setCurrentText("5초")
        self.opt_comboBox_bufTime.setObjectName("opt_comboBox_bufTime")
        self.opt_comboBox_bufTime.addItem("")
        self.opt_comboBox_bufTime.addItem("")
        self.opt_comboBox_bufTime.addItem("")
        self.opt_comboBox_bufTime.addItem("")
        self.opt_horizontalLayout_6.addWidget(self.opt_comboBox_bufTime)
		######## 설정.영상 검출 옵션 설정 end
		
		######## 설정.오토 포커싱 옵션 설정 start
        self.opt_groupBox_bot = QtWidgets.QGroupBox(self.tab_opt)
        self.opt_groupBox_bot.setGeometry(QtCore.QRect(60, 500, 1161, 171))
        self.opt_groupBox_bot.setObjectName("opt_groupBox_bot")
        self.opt_label_cn2 = QtWidgets.QLabel(self.opt_groupBox_bot)
        self.opt_label_cn2.setGeometry(QtCore.QRect(50, 120, 591, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.opt_label_cn2.setFont(font)
        self.opt_label_cn2.setScaledContents(False)
        self.opt_label_cn2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.opt_label_cn2.setWordWrap(True)
        self.opt_label_cn2.setObjectName("opt_label_cn2")
        self.widget7 = QtWidgets.QWidget(self.opt_groupBox_bot)
        self.widget7.setGeometry(QtCore.QRect(50, 40, 177, 22))
        self.widget7.setObjectName("widget7")
        self.opt_horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget7)
        self.opt_horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.opt_horizontalLayout_7.setObjectName("opt_horizontalLayout_7")
        self.opt_label_afcBoxHei = QtWidgets.QLabel(self.widget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_afcBoxHei.setFont(font)
        self.opt_label_afcBoxHei.setScaledContents(False)
        self.opt_label_afcBoxHei.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_afcBoxHei.setWordWrap(True)
        self.opt_label_afcBoxHei.setObjectName("opt_label_afcBoxHei")
        self.opt_horizontalLayout_7.addWidget(self.opt_label_afcBoxHei)
        self.opt_spinBox_widthValue = QtWidgets.QSpinBox(self.widget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_spinBox_widthValue.setFont(font)
        self.opt_spinBox_widthValue.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_spinBox_widthValue.setMaximum(2000)
        self.opt_spinBox_widthValue.setProperty("value", 600)
        self.opt_spinBox_widthValue.setObjectName("opt_spinBox_widthValue")
        self.opt_horizontalLayout_7.addWidget(self.opt_spinBox_widthValue)
        self.widget8 = QtWidgets.QWidget(self.opt_groupBox_bot)
        self.widget8.setGeometry(QtCore.QRect(50, 80, 177, 22))
        self.widget8.setObjectName("widget8")
        self.opt_horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget8)
        self.opt_horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.opt_horizontalLayout_8.setObjectName("opt_horizontalLayout_8")
        self.opt_label_afcBoxWid = QtWidgets.QLabel(self.widget8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_afcBoxWid.setFont(font)
        self.opt_label_afcBoxWid.setScaledContents(False)
        self.opt_label_afcBoxWid.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_afcBoxWid.setWordWrap(True)
        self.opt_label_afcBoxWid.setObjectName("opt_label_afcBoxWid")
        self.opt_horizontalLayout_8.addWidget(self.opt_label_afcBoxWid)
        self.opt_spinBox_heightValue = QtWidgets.QSpinBox(self.widget8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_spinBox_heightValue.setFont(font)
        self.opt_spinBox_heightValue.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_spinBox_heightValue.setMaximum(2000)
        self.opt_spinBox_heightValue.setProperty("value", 300)
        self.opt_spinBox_heightValue.setObjectName("opt_spinBox_heightValue")
        self.opt_horizontalLayout_8.addWidget(self.opt_spinBox_heightValue)
		######## 설정.오토 포커싱 옵션 설정 end
		
		######## 탭 정보 생성 처리
		self.mainTabWidget.addTab(self.tab_afc, "오토포커싱")
		self.mainTabWidget.addTab(self.tab_ext, "영상검출")
		self.mainTabWidget.addTab(self.tab_opt, "설정")
		#self.mainTabWidget.addTab(self.tab_opt, "설정")
        
		######## 폼 액션 처리
        self.horizontalLayout_2.addWidget(self.mainTabWidget)
        self.action = QtWidgets.QAction(Form)
        self.action.setObjectName("action")
        self.retranslateUi(Form)
        self.mainTabWidget.setCurrentIndex(0)
        self.opt_comboBox_bufTime.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)
		
		
		######## tab key로 인한 이동 순서 설정 start / Form.setTabOrder(A, B) -> Form.setTabOrder(B, C)
        Form.setTabOrder(self.mainTabWidget, self.ext_pushButton_localUpload)
        Form.setTabOrder(self.ext_pushButton_localUpload, self.ext_pushButton_urlUpload)
        Form.setTabOrder(self.ext_pushButton_urlUpload, self.ext_pushButton_mdDown)
        Form.setTabOrder(self.ext_pushButton_mdDown, self.ext_pushButton_startExt)
        Form.setTabOrder(self.ext_pushButton_startExt, self.ext_tableWidget_extResultList)
        Form.setTabOrder(self.ext_tableWidget_extResultList, self.ext_pushButton_allClear)
        Form.setTabOrder(self.ext_pushButton_allClear, self.ext_pushButton_selectDelete)
        Form.setTabOrder(self.ext_pushButton_selectDelete, self.ext_pushButton_allSave)
        Form.setTabOrder(self.ext_pushButton_allSave, self.ext_pushButton_selectSave)
        Form.setTabOrder(self.ext_pushButton_selectSave, self.ext_tableWidget_classList)
        Form.setTabOrder(self.ext_tableWidget_classList, self.afc_pushButton_localUpload)
        Form.setTabOrder(self.afc_pushButton_localUpload, self.afc_pushButton_urlUpload)
        Form.setTabOrder(self.afc_pushButton_urlUpload, self.afc_pushButton_mdDown)
        Form.setTabOrder(self.afc_pushButton_mdDown, self.afc_pushButton_startExt)
        Form.setTabOrder(self.afc_pushButton_startExt, self.afc_scrollArea_classList)
        Form.setTabOrder(self.afc_scrollArea_classList, self.opt_lineEdit_urlSaveDir)
        Form.setTabOrder(self.opt_lineEdit_urlSaveDir, self.opt_pushButton_urlDownDir)
        Form.setTabOrder(self.opt_pushButton_urlDownDir, self.opt_lineEdit_saveDir)
        Form.setTabOrder(self.opt_lineEdit_saveDir, self.opt_pushButton_saveDir)
        Form.setTabOrder(self.opt_pushButton_saveDir, self.opt_comboBox_downFileFmt)
        Form.setTabOrder(self.opt_comboBox_downFileFmt, self.opt_comboBox_downFileDef)
        Form.setTabOrder(self.opt_comboBox_downFileDef, self.opt_comboBox_coordFmt)
        Form.setTabOrder(self.opt_comboBox_coordFmt, self.opt_comboBox_bufTime)
        Form.setTabOrder(self.opt_comboBox_bufTime, self.opt_spinBox_widthValue)
        Form.setTabOrder(self.opt_spinBox_widthValue, self.opt_spinBox_heightValue)
		######## tab key로 인한 이동 순서 설정 end
		
		

    def retranslateUi(self, Form):
	"""
	# 테이블 데이터 / 버튼명 데이터  label text 데이터 입력 처리부
	# 확인 후 해당 형태로 데이터 입력
	"""
        # 어플리케이션 네임
		Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Human?", None, -1))
		
		# 영상검출.검출결과리스트 테이블 헤더 설정
        self.ext_tableWidget_extResultList.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Form", "썸네일", None, -1))
        self.ext_tableWidget_extResultList.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Form", "검출구간", None, -1))
        self.ext_tableWidget_extResultList.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Form", "검출구간수정", None, -1))
        self.ext_tableWidget_extResultList.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Form", "라벨명", None, -1))
        self.ext_tableWidget_extResultList.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Form", "기타정보", None, -1))
        self.ext_tableWidget_extResultList.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("Form", "선택", None, -1))
        __sortingEnabled = self.ext_tableWidget_extResultList.isSortingEnabled()
		
		# 영상검출.검출결과리스트 테이블 임의 Row 값 입력 (해당 내역 참조해서 값 입력 function 생성)
        self.ext_tableWidget_extResultList.setSortingEnabled(False)
        self.ext_tableWidget_extResultList.item(0, 0).setText(QtWidgets.QApplication.translate("Form", "썸네일 이미지 추가예정", None, -1))
        self.ext_tableWidget_extResultList.item(0, 1).setText(QtWidgets.QApplication.translate("Form", "00:22-00:27", None, -1))
        self.ext_tableWidget_extResultList.item(0, 2).setText(QtWidgets.QApplication.translate("Form", "셀렉트바 추가", None, -1))
        self.ext_tableWidget_extResultList.item(0, 3).setText(QtWidgets.QApplication.translate("Form", "아이린", None, -1))
        self.ext_tableWidget_extResultList.item(0, 4).setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.ext_tableWidget_extResultList.item(0, 5).setText(QtWidgets.QApplication.translate("Form", "체크박스 추가", None, -1))
        self.ext_tableWidget_extResultList.item(1, 0).setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.ext_tableWidget_extResultList.item(1, 1).setText(QtWidgets.QApplication.translate("Form", "00:35-00:40", None, -1))
        self.ext_tableWidget_extResultList.item(1, 2).setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.ext_tableWidget_extResultList.item(1, 3).setText(QtWidgets.QApplication.translate("Form", "아이린", None, -1))
        self.ext_tableWidget_extResultList.item(1, 4).setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.ext_tableWidget_extResultList.item(1, 5).setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.ext_tableWidget_extResultList.item(2, 0).setText(QtWidgets.QApplication.translate("Form", "2", None, -1))
        self.ext_tableWidget_extResultList.item(2, 1).setText(QtWidgets.QApplication.translate("Form", "00:50-00:55", None, -1))
        self.ext_tableWidget_extResultList.item(2, 2).setText(QtWidgets.QApplication.translate("Form", "2", None, -1))
        self.ext_tableWidget_extResultList.item(2, 3).setText(QtWidgets.QApplication.translate("Form", "아이린", None, -1))
        self.ext_tableWidget_extResultList.item(2, 4).setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.ext_tableWidget_extResultList.item(2, 5).setText(QtWidgets.QApplication.translate("Form", "2", None, -1))
        self.ext_tableWidget_extResultList.item(3, 0).setText(QtWidgets.QApplication.translate("Form", "3", None, -1))
        self.ext_tableWidget_extResultList.item(3, 1).setText(QtWidgets.QApplication.translate("Form", "01:13-01:18", None, -1))
        self.ext_tableWidget_extResultList.item(3, 2).setText(QtWidgets.QApplication.translate("Form", "3", None, -1))
        self.ext_tableWidget_extResultList.item(3, 3).setText(QtWidgets.QApplication.translate("Form", "아이린", None, -1))
        self.ext_tableWidget_extResultList.item(3, 4).setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.ext_tableWidget_extResultList.item(3, 5).setText(QtWidgets.QApplication.translate("Form", "3", None, -1))
        self.ext_tableWidget_extResultList.setSortingEnabled(__sortingEnabled)
		
		# 영상 검출탭 버튼 및 라벨 설정
        self.ext_label_extMd.setText(QtWidgets.QApplication.translate("Form", "Video Area", None, -1))
        self.ext_label_extResultList.setText(QtWidgets.QApplication.translate("Form", "검출 내역", None, -1))
        self.ext_label_classList.setText(QtWidgets.QApplication.translate("Form", "검출 대상 리스트", None, -1))
        self.ext_pushButton_startExt.setText(QtWidgets.QApplication.translate("Form", "검출 시작", None, -1))
        self.ext_pushButton_allClear.setText(QtWidgets.QApplication.translate("Form", "초기화", None, -1))
        self.ext_pushButton_selectDelete.setText(QtWidgets.QApplication.translate("Form", "선택 삭제", None, -1))
        self.ext_pushButton_allSave.setText(QtWidgets.QApplication.translate("Form", "전체 내려받기", None, -1))
        self.ext_pushButton_selectSave.setText(QtWidgets.QApplication.translate("Form", "선택 내려받기", None, -1))
        self.ext_pushButton_localUpload.setText(QtWidgets.QApplication.translate("Form", "로컬 업로드", None, -1))
        self.ext_pushButton_urlUpload.setText(QtWidgets.QApplication.translate("Form", "URL 업로드", None, -1))
        self.ext_pushButton_mdDown.setText(QtWidgets.QApplication.translate("Form", "영상 내려받기", None, -1))
		
		# 오토포커싱탭 버튼 및 라벨 설정
        self.afc_label_14_beforeMd.setText(QtWidgets.QApplication.translate("Form", "Original Video Area", None, -1))
        self.afc_afc_label_afterMd.setText(QtWidgets.QApplication.translate("Form", "Focus Video Area", None, -1))
        self.afc_label_classList.setText(QtWidgets.QApplication.translate("Form", "검출 대상 리스트", None, -1))
        self.afc_pushButton_startExt.setText(QtWidgets.QApplication.translate("Form", "검출 시작", None, -1))
        self.afc_label_beforeMd.setText(QtWidgets.QApplication.translate("Form", "원본 영상", None, -1))
        self.afc_label_afterMd.setText(QtWidgets.QApplication.translate("Form", "포커싱 영상", None, -1))
        self.afc_pushButton_localUpload.setText(QtWidgets.QApplication.translate("Form", "로컬 업로드", None, -1))
        self.afc_pushButton_urlUpload.setText(QtWidgets.QApplication.translate("Form", "URL 업로드", None, -1))
        self.afc_pushButton_mdDown.setText(QtWidgets.QApplication.translate("Form", "영상 내려받기", None, -1))
		
		# 설정탭 버튼 및 라벨
        self.opt_groupBox_top.setTitle(QtWidgets.QApplication.translate("Form", "공통 옵션 설정", None, -1))
        self.opt_label_saveFmt.setText(QtWidgets.QApplication.translate("Form", "내려받기 확장자", None, -1))
        self.opt_comboBox_downFileFmt.setItemText(24, QtWidgets.QApplication.translate("Form", "확장자 선택", None, -1))
        self.opt_comboBox_downFileFmt.setItemText(25, QtWidgets.QApplication.translate("Form", "mp4", None, -1))
        self.opt_label_coordFmt.setText(QtWidgets.QApplication.translate("Form", "좌표파일 확장자 선택", None, -1))
        self.opt_comboBox_coordFmt.setItemText(26, QtWidgets.QApplication.translate("Form", "확장자 선택", None, -1))
        self.opt_label_saveMdQual.setText(QtWidgets.QApplication.translate("Form", "내려받기 화질 선택", None, -1))
        self.opt_comboBox_downFileDef.setItemText(27, QtWidgets.QApplication.translate("Form", "화질 선택", None, -1))
        self.opt_label_urlSaveDir.setText(QtWidgets.QApplication.translate("Form", "URL 저장 파일 경로", None, -1))
        self.opt_pushButton_urlDownDir.setText(QtWidgets.QApplication.translate("Form", "폴더찾기", None, -1))
        self.opt_label_localSaveDir.setText(QtWidgets.QApplication.translate("Form", "내려받기 저장 경로", None, -1))
        self.opt_pushButton_saveDir.setText(QtWidgets.QApplication.translate("Form", "폴더찾기", None, -1))
        self.opt_groupBox_mid.setTitle(QtWidgets.QApplication.translate("Form", "영상 검출 옵션 설정", None, -1))
        self.opt_groupBox_4.setTitle(QtWidgets.QApplication.translate("Form", "GroupBox", None, -1))
        self.opt_label_cn1.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" color:#ff0000;\">※ 검출 내역 한 건당 설정 할 수 있는 버퍼의 범위는 00:01 ~ 00:05 초 사이로 설정 할 수 있습니다.</span></p></body></html>", None, -1))
        self.opt_label_extButTm.setText(QtWidgets.QApplication.translate("Form", "추출 영상 버퍼 시간", None, -1))
        self.opt_comboBox_bufTime.setItemText(28, QtWidgets.QApplication.translate("Form", "버퍼(초)선택", None, -1))
        self.opt_comboBox_bufTime.setItemText(29, QtWidgets.QApplication.translate("Form", "1초", None, -1))
        self.opt_comboBox_bufTime.setItemText(30, QtWidgets.QApplication.translate("Form", "3초", None, -1))
        self.opt_comboBox_bufTime.setItemText(31, QtWidgets.QApplication.translate("Form", "5초", None, -1))
        self.opt_groupBox_bot.setTitle(QtWidgets.QApplication.translate("Form", "오토 포커싱 옵션 설정", None, -1))
        self.opt_label_cn2.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" color:#ff0000;\">※ 포커싱 박스의 넓이 및 높이는 포커싱 영상의 해상도 보다 클 수 없습니다.</span></p></body></html>", None, -1))
        self.opt_label_afcBoxHei.setText(QtWidgets.QApplication.translate("Form", "포커싱 박스 높이", None, -1))
        self.opt_label_afcBoxWid.setText(QtWidgets.QApplication.translate("Form", "포커싱 박스 넓이", None, -1))
        self.action.setText(QtWidgets.QApplication.translate("Form", "테스트", None, -1))
        self.action.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>툴팁화면</p></body></html>", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

