# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui',
# licensing of 'mainWindow.ui' applies.
#
# Created: Tue Aug 27 09:38:04 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        ########
        #	Main Form Default
        #	- 메인 폼
        ########
        Form.setObjectName("Form")
        Form.resize(1280, 840)
        Form.setMinimumSize(QtCore.QSize(1280, 840))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mainTabWidget = QtWidgets.QTabWidget(Form)
        self.mainTabWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("나눔고딕코딩")
        font.setPointSize(14)

        ########
        #	Main tab Default
        #	- 탭 전체 공통 옵션
        ########
        self.mainTabWidget.setFont(font)
        self.mainTabWidget.setObjectName("mainTabWidget")


        ########
        #	extTab Default
        #	- 영상검출탭
        ########
        self.tab_ext = QtWidgets.QWidget()
        self.tab_ext.setEnabled(True)
        self.tab_ext.setObjectName("tab_ext")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_ext)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ext_verticalLayout_top = QtWidgets.QVBoxLayout()
        self.ext_verticalLayout_top.setObjectName("ext_verticalLayout_top")
        self.ext_horizontalLayout_top = QtWidgets.QHBoxLayout()
        self.ext_horizontalLayout_top.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ext_horizontalLayout_top.setObjectName("ext_horizontalLayout_top")
        self.ext_pushButton_localUpload = QtWidgets.QPushButton(self.tab_ext)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ext_pushButton_localUpload.sizePolicy().hasHeightForWidth())
        self.ext_pushButton_localUpload.setSizePolicy(sizePolicy)
        self.ext_pushButton_localUpload.setMinimumSize(QtCore.QSize(0, 57))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ext_pushButton_localUpload.setFont(font)
        self.ext_pushButton_localUpload.setObjectName("ext_pushButton_localUpload")
        self.ext_horizontalLayout_top.addWidget(self.ext_pushButton_localUpload)
        self.ext_pushButton_mdDown = QtWidgets.QPushButton(self.tab_ext)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ext_pushButton_mdDown.sizePolicy().hasHeightForWidth())
        self.ext_pushButton_mdDown.setSizePolicy(sizePolicy)
        self.ext_pushButton_mdDown.setMinimumSize(QtCore.QSize(0, 57))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ext_pushButton_mdDown.setFont(font)
        self.ext_pushButton_mdDown.setObjectName("ext_pushButton_mdDown")
        self.ext_horizontalLayout_top.addWidget(self.ext_pushButton_mdDown)
        self.ext_pushButton_urlUpload = QtWidgets.QPushButton(self.tab_ext)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ext_pushButton_urlUpload.sizePolicy().hasHeightForWidth())
        self.ext_pushButton_urlUpload.setSizePolicy(sizePolicy)
        self.ext_pushButton_urlUpload.setMinimumSize(QtCore.QSize(0, 57))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ext_pushButton_urlUpload.setFont(font)
        self.ext_pushButton_urlUpload.setObjectName("ext_pushButton_urlUpload")
        self.ext_horizontalLayout_top.addWidget(self.ext_pushButton_urlUpload)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ext_horizontalLayout_top.addItem(spacerItem)
        self.ext_verticalLayout_top.addLayout(self.ext_horizontalLayout_top)
        self.verticalLayout_8.addLayout(self.ext_verticalLayout_top)
        self.ext_splitter_Md = QtWidgets.QSplitter(self.tab_ext)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ext_splitter_Md.sizePolicy().hasHeightForWidth())
        self.ext_splitter_Md.setSizePolicy(sizePolicy)
        self.ext_splitter_Md.setOrientation(QtCore.Qt.Horizontal)
        self.ext_splitter_Md.setObjectName("ext_splitter_Md")
        self.ext_widget_video_Md = QtWidgets.QWidget(self.ext_splitter_Md)
        self.ext_widget_video_Md.setStyleSheet("border: 1px solid gray;")
        self.ext_widget_video_Md.setObjectName("ext_widget_video_Md")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.ext_widget_video_Md)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.ext_label_extMd = QtWidgets.QLabel(self.ext_widget_video_Md)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ext_label_extMd.sizePolicy().hasHeightForWidth())
        self.ext_label_extMd.setSizePolicy(sizePolicy)
        self.ext_label_extMd.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.ext_label_extMd.setFont(font)
        self.ext_label_extMd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ext_label_extMd.setStyleSheet("border: 1px solid gray;")
        self.ext_label_extMd.setAlignment(QtCore.Qt.AlignCenter)
        self.ext_label_extMd.setObjectName("ext_label_extMd")
        self.verticalLayout_7.addWidget(self.ext_label_extMd)
        self.ext_horizontalLayout_mid1 = QtWidgets.QHBoxLayout()
        self.ext_horizontalLayout_mid1.setObjectName("ext_horizontalLayout_mid1")
        self.ext_horizontalLayout_mid2 = QtWidgets.QHBoxLayout()
        self.ext_horizontalLayout_mid2.setObjectName("ext_horizontalLayout_mid2")
        self.ext_pushButton_play = QtWidgets.QPushButton(self.ext_widget_video_Md)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ext_pushButton_play.sizePolicy().hasHeightForWidth())
        self.ext_pushButton_play.setSizePolicy(sizePolicy)
        self.ext_pushButton_play.setObjectName("ext_pushButton_play")
        self.ext_horizontalLayout_mid2.addWidget(self.ext_pushButton_play)
        self.ext_pushButton_pause = QtWidgets.QPushButton(self.ext_widget_video_Md)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ext_pushButton_pause.sizePolicy().hasHeightForWidth())
        self.ext_pushButton_pause.setSizePolicy(sizePolicy)
        self.ext_pushButton_pause.setObjectName("ext_pushButton_pause")
        self.ext_horizontalLayout_mid2.addWidget(self.ext_pushButton_pause)
        self.ext_pushButton_stop = QtWidgets.QPushButton(self.ext_widget_video_Md)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ext_pushButton_stop.sizePolicy().hasHeightForWidth())
        self.ext_pushButton_stop.setSizePolicy(sizePolicy)
        self.ext_pushButton_stop.setObjectName("ext_pushButton_stop")
        self.ext_horizontalLayout_mid2.addWidget(self.ext_pushButton_stop)
        self.ext_horizontalLayout_mid1.addLayout(self.ext_horizontalLayout_mid2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ext_horizontalLayout_mid1.addItem(spacerItem1)
        self.ext_video_time = QtWidgets.QLabel(self.ext_widget_video_Md)
        self.ext_video_time.setObjectName("ext_video_time")
        self.ext_horizontalLayout_mid1.addWidget(self.ext_video_time)
        self.verticalLayout_7.addLayout(self.ext_horizontalLayout_mid1)
        self.ext_widget_result_Md = QtWidgets.QWidget(self.ext_splitter_Md)
        self.ext_widget_result_Md.setStyleSheet("border: 1px solid gray;")
        self.ext_widget_result_Md.setObjectName("ext_widget_result_Md")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ext_widget_result_Md)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ext_label_extResultList = QtWidgets.QLabel(self.ext_widget_result_Md)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.ext_label_extResultList.setFont(font)
        self.ext_label_extResultList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ext_label_extResultList.setAlignment(QtCore.Qt.AlignCenter)
        self.ext_label_extResultList.setObjectName("ext_label_extResultList")
        self.horizontalLayout_3.addWidget(self.ext_label_extResultList)
        spacerItem2 = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.ext_tableWidget_extResultList = QtWidgets.QTableWidget(self.ext_widget_result_Md)
        self.ext_tableWidget_extResultList.setMinimumSize(QtCore.QSize(160, 0))
        self.ext_tableWidget_extResultList.setObjectName("ext_tableWidget_extResultList")
        self.ext_tableWidget_extResultList.setColumnCount(6)
        self.ext_tableWidget_extResultList.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ext_tableWidget_extResultList.setItem(3, 5, item)
        self.verticalLayout_3.addWidget(self.ext_tableWidget_extResultList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ext_pushButton_allClear = QtWidgets.QPushButton(self.ext_widget_result_Md)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ext_pushButton_allClear.setFont(font)
        self.ext_pushButton_allClear.setObjectName("ext_pushButton_allClear")
        self.horizontalLayout.addWidget(self.ext_pushButton_allClear)
        self.ext_pushButton_selectDelete = QtWidgets.QPushButton(self.ext_widget_result_Md)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ext_pushButton_selectDelete.setFont(font)
        self.ext_pushButton_selectDelete.setObjectName("ext_pushButton_selectDelete")
        self.horizontalLayout.addWidget(self.ext_pushButton_selectDelete)
        self.ext_pushButton_allSave = QtWidgets.QPushButton(self.ext_widget_result_Md)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ext_pushButton_allSave.setFont(font)
        self.ext_pushButton_allSave.setObjectName("ext_pushButton_allSave")
        self.horizontalLayout.addWidget(self.ext_pushButton_allSave)
        self.ext_pushButton_selectSave = QtWidgets.QPushButton(self.ext_widget_result_Md)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ext_pushButton_selectSave.setFont(font)
        self.ext_pushButton_selectSave.setObjectName("ext_pushButton_selectSave")
        self.horizontalLayout.addWidget(self.ext_pushButton_selectSave)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_8.addWidget(self.ext_splitter_Md)
        self.ext_horizontalLayout_bot_main = QtWidgets.QHBoxLayout()
        self.ext_horizontalLayout_bot_main.setObjectName("ext_horizontalLayout_bot_main")
        self.ext_verticalLayout_bot_content = QtWidgets.QVBoxLayout()
        self.ext_verticalLayout_bot_content.setObjectName("ext_verticalLayout_bot_content")
        self.ext_horizontalLayout_bot_titleHeader = QtWidgets.QHBoxLayout()
        self.ext_horizontalLayout_bot_titleHeader.setObjectName("ext_horizontalLayout_bot_titleHeader")
        self.ext_label_classList = QtWidgets.QLabel(self.tab_ext)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.ext_label_classList.setFont(font)
        self.ext_label_classList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ext_label_classList.setAlignment(QtCore.Qt.AlignCenter)
        self.ext_label_classList.setObjectName("ext_label_classList")
        self.ext_horizontalLayout_bot_titleHeader.addWidget(self.ext_label_classList)
        spacerItem3 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ext_horizontalLayout_bot_titleHeader.addItem(spacerItem3)
        self.ext_verticalLayout_bot_content.addLayout(self.ext_horizontalLayout_bot_titleHeader)
        self.ext_tableWidget_classList = QtWidgets.QTableWidget(self.tab_ext)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ext_tableWidget_classList.sizePolicy().hasHeightForWidth())
        self.ext_tableWidget_classList.setSizePolicy(sizePolicy)
        self.ext_tableWidget_classList.setMaximumSize(QtCore.QSize(16777215, 160))
        self.ext_tableWidget_classList.setObjectName("ext_tableWidget_classList")
        self.ext_tableWidget_classList.setColumnCount(0)
        self.ext_tableWidget_classList.setRowCount(0)
        self.ext_verticalLayout_bot_content.addWidget(self.ext_tableWidget_classList)
        self.ext_horizontalLayout_bot_main.addLayout(self.ext_verticalLayout_bot_content)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ext_horizontalLayout_bot_main.addItem(spacerItem4)
        self.ext_pushButton_startExt = QtWidgets.QPushButton(self.tab_ext)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ext_pushButton_startExt.sizePolicy().hasHeightForWidth())
        self.ext_pushButton_startExt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ext_pushButton_startExt.setFont(font)
        self.ext_pushButton_startExt.setObjectName("ext_pushButton_startExt")
        self.ext_horizontalLayout_bot_main.addWidget(self.ext_pushButton_startExt)
        self.verticalLayout_8.addLayout(self.ext_horizontalLayout_bot_main)
        # self.mainTabWidget.addTab(self.tab_ext, "영상검출")

        ########
        #	afcTab Default
        #	- 오토포커싱탭
        ########
        self.tab_afc = QtWidgets.QWidget()
        self.tab_afc.setObjectName("tab_afc")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_afc)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.afc_verticalLayout_top = QtWidgets.QVBoxLayout()
        self.afc_verticalLayout_top.setObjectName("afc_verticalLayout_top")
        self.afc_horizontalLayout_top = QtWidgets.QHBoxLayout()
        self.afc_horizontalLayout_top.setObjectName("afc_horizontalLayout_top")
        self.afc_pushButton_localUpload = QtWidgets.QPushButton(self.tab_afc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_pushButton_localUpload.sizePolicy().hasHeightForWidth())
        self.afc_pushButton_localUpload.setSizePolicy(sizePolicy)
        self.afc_pushButton_localUpload.setMinimumSize(QtCore.QSize(0, 57))
        self.afc_pushButton_localUpload.setMaximumSize(QtCore.QSize(95, 57))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.afc_pushButton_localUpload.setFont(font)
        self.afc_pushButton_localUpload.setObjectName("afc_pushButton_localUpload")
        self.afc_horizontalLayout_top.addWidget(self.afc_pushButton_localUpload)
        self.afc_pushButton_mdDown = QtWidgets.QPushButton(self.tab_afc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_pushButton_mdDown.sizePolicy().hasHeightForWidth())
        self.afc_pushButton_mdDown.setSizePolicy(sizePolicy)
        self.afc_pushButton_mdDown.setMinimumSize(QtCore.QSize(0, 57))
        self.afc_pushButton_mdDown.setMaximumSize(QtCore.QSize(105, 57))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.afc_pushButton_mdDown.setFont(font)
        self.afc_pushButton_mdDown.setObjectName("afc_pushButton_mdDown")
        self.afc_horizontalLayout_top.addWidget(self.afc_pushButton_mdDown)
        self.afc_pushButton_urlUpload = QtWidgets.QPushButton(self.tab_afc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_pushButton_urlUpload.sizePolicy().hasHeightForWidth())
        self.afc_pushButton_urlUpload.setSizePolicy(sizePolicy)
        self.afc_pushButton_urlUpload.setMinimumSize(QtCore.QSize(0, 57))
        self.afc_pushButton_urlUpload.setMaximumSize(QtCore.QSize(95, 57))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.afc_pushButton_urlUpload.setFont(font)
        self.afc_pushButton_urlUpload.setObjectName("afc_pushButton_urlUpload")
        self.afc_horizontalLayout_top.addWidget(self.afc_pushButton_urlUpload)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.afc_horizontalLayout_top.addItem(spacerItem5)
        self.afc_verticalLayout_top.addLayout(self.afc_horizontalLayout_top)
        self.verticalLayout_5.addLayout(self.afc_verticalLayout_top)
        self.afc_splitter_Md = QtWidgets.QSplitter(self.tab_afc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_splitter_Md.sizePolicy().hasHeightForWidth())
        self.afc_splitter_Md.setSizePolicy(sizePolicy)
        self.afc_splitter_Md.setOrientation(QtCore.Qt.Horizontal)
        self.afc_splitter_Md.setObjectName("afc_splitter_Md")
        self.afc_widget_before_Md = QtWidgets.QWidget(self.afc_splitter_Md)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_widget_before_Md.sizePolicy().hasHeightForWidth())
        self.afc_widget_before_Md.setSizePolicy(sizePolicy)
        self.afc_widget_before_Md.setStyleSheet("border: 1px solid gray;")
        self.afc_widget_before_Md.setObjectName("afc_widget_before_Md")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.afc_widget_before_Md)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.afc_label_before_Md = QtWidgets.QLabel(self.afc_widget_before_Md)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_label_before_Md.sizePolicy().hasHeightForWidth())
        self.afc_label_before_Md.setSizePolicy(sizePolicy)
        self.afc_label_before_Md.setMinimumSize(QtCore.QSize(160, 450))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.afc_label_before_Md.setFont(font)
        self.afc_label_before_Md.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.afc_label_before_Md.setStyleSheet("border: 1px solid gray;")
        self.afc_label_before_Md.setAlignment(QtCore.Qt.AlignCenter)
        self.afc_label_before_Md.setObjectName("afc_label_before_Md")
        self.verticalLayout.addWidget(self.afc_label_before_Md)
        self.afc_horizontalLayout_mid1 = QtWidgets.QHBoxLayout()
        self.afc_horizontalLayout_mid1.setObjectName("afc_horizontalLayout_mid1")
        self.afc_horizontalLayout_mid2 = QtWidgets.QHBoxLayout()
        self.afc_horizontalLayout_mid2.setObjectName("afc_horizontalLayout_mid2")
        self.afc_pushButton_play = QtWidgets.QPushButton(self.afc_widget_before_Md)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_pushButton_play.sizePolicy().hasHeightForWidth())
        self.afc_pushButton_play.setSizePolicy(sizePolicy)
        self.afc_pushButton_play.setObjectName("afc_pushButton_play")
        self.afc_horizontalLayout_mid2.addWidget(self.afc_pushButton_play)
        self.afc_pushButton_pause = QtWidgets.QPushButton(self.afc_widget_before_Md)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_pushButton_pause.sizePolicy().hasHeightForWidth())
        self.afc_pushButton_pause.setSizePolicy(sizePolicy)
        self.afc_pushButton_pause.setObjectName("afc_pushButton_pause")
        self.afc_horizontalLayout_mid2.addWidget(self.afc_pushButton_pause)
        self.afc_pushButton_stop = QtWidgets.QPushButton(self.afc_widget_before_Md)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_pushButton_stop.sizePolicy().hasHeightForWidth())
        self.afc_pushButton_stop.setSizePolicy(sizePolicy)
        self.afc_pushButton_stop.setObjectName("afc_pushButton_stop")
        self.afc_horizontalLayout_mid2.addWidget(self.afc_pushButton_stop)
        self.afc_horizontalLayout_mid1.addLayout(self.afc_horizontalLayout_mid2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.afc_horizontalLayout_mid1.addItem(spacerItem6)
        self.afc_before_time = QtWidgets.QLabel(self.afc_widget_before_Md)
        self.afc_before_time.setObjectName("afc_before_time")
        self.afc_horizontalLayout_mid1.addWidget(self.afc_before_time)
        self.verticalLayout.addLayout(self.afc_horizontalLayout_mid1)
        self.afc_widget_after_Md = QtWidgets.QWidget(self.afc_splitter_Md)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_widget_after_Md.sizePolicy().hasHeightForWidth())
        self.afc_widget_after_Md.setSizePolicy(sizePolicy)
        self.afc_widget_after_Md.setStyleSheet("border: 1px solid gray;")
        self.afc_widget_after_Md.setObjectName("afc_widget_after_Md")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.afc_widget_after_Md)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.afc_label_after_Md = QtWidgets.QLabel(self.afc_widget_after_Md)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_label_after_Md.sizePolicy().hasHeightForWidth())
        self.afc_label_after_Md.setSizePolicy(sizePolicy)
        self.afc_label_after_Md.setMinimumSize(QtCore.QSize(160, 450))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.afc_label_after_Md.setFont(font)
        self.afc_label_after_Md.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.afc_label_after_Md.setStyleSheet("border: 1px solid gray;")
        self.afc_label_after_Md.setAlignment(QtCore.Qt.AlignCenter)
        self.afc_label_after_Md.setObjectName("afc_label_after_Md")
        self.verticalLayout_2.addWidget(self.afc_label_after_Md)
        self.afc_horizontalLayout_mid1_2 = QtWidgets.QHBoxLayout()
        self.afc_horizontalLayout_mid1_2.setObjectName("afc_horizontalLayout_mid1_2")
        self.afc_horizontalLayout_mid2_2 = QtWidgets.QHBoxLayout()
        self.afc_horizontalLayout_mid2_2.setObjectName("afc_horizontalLayout_mid2_2")
        self.afc_pushButton_play_2 = QtWidgets.QPushButton(self.afc_widget_after_Md)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_pushButton_play_2.sizePolicy().hasHeightForWidth())
        self.afc_pushButton_play_2.setSizePolicy(sizePolicy)
        self.afc_pushButton_play_2.setObjectName("afc_pushButton_play_2")
        self.afc_horizontalLayout_mid2_2.addWidget(self.afc_pushButton_play_2)
        self.afc_pushButton_pause_2 = QtWidgets.QPushButton(self.afc_widget_after_Md)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_pushButton_pause_2.sizePolicy().hasHeightForWidth())
        self.afc_pushButton_pause_2.setSizePolicy(sizePolicy)
        self.afc_pushButton_pause_2.setObjectName("afc_pushButton_pause_2")
        self.afc_horizontalLayout_mid2_2.addWidget(self.afc_pushButton_pause_2)
        self.afc_pushButton_stop_2 = QtWidgets.QPushButton(self.afc_widget_after_Md)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_pushButton_stop_2.sizePolicy().hasHeightForWidth())
        self.afc_pushButton_stop_2.setSizePolicy(sizePolicy)
        self.afc_pushButton_stop_2.setObjectName("afc_pushButton_stop_2")
        self.afc_horizontalLayout_mid2_2.addWidget(self.afc_pushButton_stop_2)
        self.afc_horizontalLayout_mid1_2.addLayout(self.afc_horizontalLayout_mid2_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.afc_horizontalLayout_mid1_2.addItem(spacerItem7)
        self.label_3 = QtWidgets.QLabel(self.afc_widget_after_Md)
        self.label_3.setObjectName("label_3")
        self.afc_horizontalLayout_mid1_2.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.afc_horizontalLayout_mid1_2)
        self.verticalLayout_5.addWidget(self.afc_splitter_Md)
        self.afc_horizontalLayout_bot_main = QtWidgets.QHBoxLayout()
        self.afc_horizontalLayout_bot_main.setObjectName("afc_horizontalLayout_bot_main")
        self.afc_verticalLayout_bot_content = QtWidgets.QVBoxLayout()
        self.afc_verticalLayout_bot_content.setObjectName("afc_verticalLayout_bot_content")
        self.afc_horizontalLayout_bot_titleHeader = QtWidgets.QHBoxLayout()
        self.afc_horizontalLayout_bot_titleHeader.setObjectName("afc_horizontalLayout_bot_titleHeader")
        self.afc_label_classList = QtWidgets.QLabel(self.tab_afc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_label_classList.sizePolicy().hasHeightForWidth())
        self.afc_label_classList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.afc_label_classList.setFont(font)
        self.afc_label_classList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.afc_label_classList.setAlignment(QtCore.Qt.AlignCenter)
        self.afc_label_classList.setObjectName("afc_label_classList")
        self.afc_horizontalLayout_bot_titleHeader.addWidget(self.afc_label_classList)
        spacerItem8 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.afc_horizontalLayout_bot_titleHeader.addItem(spacerItem8)
        self.afc_verticalLayout_bot_content.addLayout(self.afc_horizontalLayout_bot_titleHeader)
        self.afc_tableWidget_classList = QtWidgets.QTableWidget(self.tab_afc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_tableWidget_classList.sizePolicy().hasHeightForWidth())
        self.afc_tableWidget_classList.setSizePolicy(sizePolicy)
        self.afc_tableWidget_classList.setMaximumSize(QtCore.QSize(16777215, 160))
        self.afc_tableWidget_classList.setObjectName("afc_tableWidget_classList")
        self.afc_tableWidget_classList.setColumnCount(0)
        self.afc_tableWidget_classList.setRowCount(0)
        self.afc_verticalLayout_bot_content.addWidget(self.afc_tableWidget_classList)
        self.afc_horizontalLayout_bot_main.addLayout(self.afc_verticalLayout_bot_content)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.afc_horizontalLayout_bot_main.addItem(spacerItem9)
        self.afc_pushButton_startExt = QtWidgets.QPushButton(self.tab_afc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afc_pushButton_startExt.sizePolicy().hasHeightForWidth())
        self.afc_pushButton_startExt.setSizePolicy(sizePolicy)
        self.afc_pushButton_startExt.setMaximumSize(QtCore.QSize(16777215, 160))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.afc_pushButton_startExt.setFont(font)
        self.afc_pushButton_startExt.setObjectName("afc_pushButton_startExt")
        self.afc_horizontalLayout_bot_main.addWidget(self.afc_pushButton_startExt)
        self.verticalLayout_5.addLayout(self.afc_horizontalLayout_bot_main)
        # self.mainTabWidget.addTab(self.tab_afc, "오토포커싱")


        ########
        #	optTab Default
        #	- 옵션설정 탭
        ########
        self.tab_opt = QtWidgets.QWidget()
        self.tab_opt.setObjectName("tab_opt")

        ######## 설정.공통옵션설정 start
        self.opt_groupBox_top = QtWidgets.QGroupBox(self.tab_opt)
        self.opt_groupBox_top.setGeometry(QtCore.QRect(60, 40, 1161, 171))
        self.opt_groupBox_top.setObjectName("opt_groupBox_top")
        self.layoutWidget = QtWidgets.QWidget(self.opt_groupBox_top)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 110, 204, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.opt_horizontalLayout3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.opt_horizontalLayout3.setContentsMargins(0, 0, 0, 0)
        self.opt_horizontalLayout3.setObjectName("opt_horizontalLayout3")
        self.opt_label_saveFmt = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_saveFmt.setFont(font)
        self.opt_label_saveFmt.setScaledContents(False)
        self.opt_label_saveFmt.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_saveFmt.setWordWrap(True)
        self.opt_label_saveFmt.setObjectName("opt_label_saveFmt")
        self.opt_horizontalLayout3.addWidget(self.opt_label_saveFmt)
        self.opt_comboBox_downFileFmt = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_comboBox_downFileFmt.setFont(font)
        self.opt_comboBox_downFileFmt.setEditable(False)
        self.opt_comboBox_downFileFmt.setCurrentText("확장자 선택")
        self.opt_comboBox_downFileFmt.setModelColumn(0)
        self.opt_comboBox_downFileFmt.setObjectName("opt_comboBox_downFileFmt")
        self.opt_comboBox_downFileFmt.addItem("")
        self.opt_comboBox_downFileFmt.addItem("")
        self.opt_horizontalLayout3.addWidget(self.opt_comboBox_downFileFmt)
        self.layoutWidget1 = QtWidgets.QWidget(self.opt_groupBox_top)
        self.layoutWidget1.setGeometry(QtCore.QRect(750, 110, 239, 24))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.opt_horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.opt_horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.opt_horizontalLayout_5.setObjectName("opt_horizontalLayout_5")
        self.opt_label_coordFmt = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_coordFmt.setFont(font)
        self.opt_label_coordFmt.setScaledContents(False)
        self.opt_label_coordFmt.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_coordFmt.setWordWrap(True)
        self.opt_label_coordFmt.setObjectName("opt_label_coordFmt")
        self.opt_horizontalLayout_5.addWidget(self.opt_label_coordFmt)
        self.opt_comboBox_coordFmt = QtWidgets.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_comboBox_coordFmt.setFont(font)
        self.opt_comboBox_coordFmt.setCurrentText("확장자 선택")
        self.opt_comboBox_coordFmt.setObjectName("opt_comboBox_coordFmt")
        self.opt_comboBox_coordFmt.addItem("")
        self.opt_horizontalLayout_5.addWidget(self.opt_comboBox_coordFmt)
        self.layoutWidget2 = QtWidgets.QWidget(self.opt_groupBox_top)
        self.layoutWidget2.setGeometry(QtCore.QRect(440, 110, 213, 24))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.opt_horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.opt_horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.opt_horizontalLayout_4.setObjectName("opt_horizontalLayout_4")
        self.opt_label_saveMdQual = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_saveMdQual.setFont(font)
        self.opt_label_saveMdQual.setScaledContents(False)
        self.opt_label_saveMdQual.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_saveMdQual.setWordWrap(True)
        self.opt_label_saveMdQual.setObjectName("opt_label_saveMdQual")
        self.opt_horizontalLayout_4.addWidget(self.opt_label_saveMdQual)
        self.opt_comboBox_downFileDef = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_comboBox_downFileDef.setFont(font)
        self.opt_comboBox_downFileDef.setCurrentText("화질 선택")
        self.opt_comboBox_downFileDef.setObjectName("opt_comboBox_downFileDef")
        self.opt_comboBox_downFileDef.addItem("")
        self.opt_horizontalLayout_4.addWidget(self.opt_comboBox_downFileDef)
        self.layoutWidget3 = QtWidgets.QWidget(self.opt_groupBox_top)
        self.layoutWidget3.setGeometry(QtCore.QRect(100, 50, 413, 30))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.opt_horizontalLayout_1 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.opt_horizontalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.opt_horizontalLayout_1.setObjectName("opt_horizontalLayout_1")
        self.opt_label_urlSaveDir = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_urlSaveDir.setFont(font)
        self.opt_label_urlSaveDir.setScaledContents(False)
        self.opt_label_urlSaveDir.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_urlSaveDir.setWordWrap(True)
        self.opt_label_urlSaveDir.setObjectName("opt_label_urlSaveDir")
        self.opt_horizontalLayout_1.addWidget(self.opt_label_urlSaveDir)
        self.opt_lineEdit_urlSaveDir = QtWidgets.QLineEdit(self.layoutWidget3)
        self.opt_lineEdit_urlSaveDir.setEnabled(True)
        self.opt_lineEdit_urlSaveDir.setObjectName("opt_lineEdit_urlSaveDir")
        self.opt_horizontalLayout_1.addWidget(self.opt_lineEdit_urlSaveDir)
        self.opt_pushButton_urlDownDir = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_pushButton_urlDownDir.setFont(font)
        self.opt_pushButton_urlDownDir.setObjectName("opt_pushButton_urlDownDir")
        self.opt_horizontalLayout_1.addWidget(self.opt_pushButton_urlDownDir)
        self.layoutWidget4 = QtWidgets.QWidget(self.opt_groupBox_top)
        self.layoutWidget4.setGeometry(QtCore.QRect(610, 50, 399, 30))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.opt_horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.opt_horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.opt_horizontalLayout_2.setObjectName("opt_horizontalLayout_2")
        self.opt_label_localSaveDir = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_localSaveDir.setFont(font)
        self.opt_label_localSaveDir.setScaledContents(False)
        self.opt_label_localSaveDir.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_localSaveDir.setWordWrap(True)
        self.opt_label_localSaveDir.setObjectName("opt_label_localSaveDir")
        self.opt_horizontalLayout_2.addWidget(self.opt_label_localSaveDir)
        self.opt_lineEdit_saveDir = QtWidgets.QLineEdit(self.layoutWidget4)
        self.opt_lineEdit_saveDir.setObjectName("opt_lineEdit_saveDir")
        self.opt_horizontalLayout_2.addWidget(self.opt_lineEdit_saveDir)
        self.opt_pushButton_saveDir = QtWidgets.QPushButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_pushButton_saveDir.setFont(font)
        self.opt_pushButton_saveDir.setObjectName("opt_pushButton_saveDir")
        self.opt_horizontalLayout_2.addWidget(self.opt_pushButton_saveDir)
        ######## 설정.공통옵션설정 end

        ######## 설정.영상 검출 옵션 설정 start
        self.opt_groupBox_mid = QtWidgets.QGroupBox(self.tab_opt)
        self.opt_groupBox_mid.setGeometry(QtCore.QRect(60, 270, 1161, 171))
        self.opt_groupBox_mid.setObjectName("opt_groupBox_mid")
        self.opt_groupBox_4 = QtWidgets.QGroupBox(self.opt_groupBox_mid)
        self.opt_groupBox_4.setGeometry(QtCore.QRect(250, 170, 1161, 171))
        self.opt_groupBox_4.setObjectName("opt_groupBox_4")
        self.opt_label_cn1 = QtWidgets.QLabel(self.opt_groupBox_mid)
        self.opt_label_cn1.setGeometry(QtCore.QRect(340, 54, 701, 75))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.opt_label_cn1.setFont(font)
        self.opt_label_cn1.setScaledContents(False)
        self.opt_label_cn1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.opt_label_cn1.setWordWrap(True)
        self.opt_label_cn1.setObjectName("opt_label_cn1")
        self.layoutWidget5 = QtWidgets.QWidget(self.opt_groupBox_mid)
        self.layoutWidget5.setGeometry(QtCore.QRect(50, 80, 238, 24))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.opt_horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.opt_horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.opt_horizontalLayout_6.setObjectName("opt_horizontalLayout_6")
        self.opt_label_extButTm = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_extButTm.setFont(font)
        self.opt_label_extButTm.setScaledContents(False)
        self.opt_label_extButTm.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_extButTm.setWordWrap(True)
        self.opt_label_extButTm.setObjectName("opt_label_extButTm")
        self.opt_horizontalLayout_6.addWidget(self.opt_label_extButTm)
        self.opt_comboBox_bufTime = QtWidgets.QComboBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.opt_comboBox_bufTime.setFont(font)
        self.opt_comboBox_bufTime.setCurrentText("5초")
        self.opt_comboBox_bufTime.setObjectName("opt_comboBox_bufTime")
        self.opt_comboBox_bufTime.addItem("")
        self.opt_comboBox_bufTime.addItem("")
        self.opt_comboBox_bufTime.addItem("")
        self.opt_comboBox_bufTime.addItem("")
        self.opt_horizontalLayout_6.addWidget(self.opt_comboBox_bufTime)
        ######## 설정.영상 검출 옵션 설정 end

        ######## 설정.오토 포커싱 옵션 설정 start
        self.opt_groupBox_bot = QtWidgets.QGroupBox(self.tab_opt)
        self.opt_groupBox_bot.setGeometry(QtCore.QRect(60, 500, 1161, 171))
        self.opt_groupBox_bot.setObjectName("opt_groupBox_bot")
        self.opt_label_cn2 = QtWidgets.QLabel(self.opt_groupBox_bot)
        self.opt_label_cn2.setGeometry(QtCore.QRect(50, 120, 591, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.opt_label_cn2.setFont(font)
        self.opt_label_cn2.setScaledContents(False)
        self.opt_label_cn2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.opt_label_cn2.setWordWrap(True)
        self.opt_label_cn2.setObjectName("opt_label_cn2")
        self.layoutWidget6 = QtWidgets.QWidget(self.opt_groupBox_bot)
        self.layoutWidget6.setGeometry(QtCore.QRect(50, 40, 177, 25))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.opt_horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.opt_horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.opt_horizontalLayout_7.setObjectName("opt_horizontalLayout_7")
        self.opt_label_afcBoxHei = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_afcBoxHei.setFont(font)
        self.opt_label_afcBoxHei.setScaledContents(False)
        self.opt_label_afcBoxHei.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_afcBoxHei.setWordWrap(True)
        self.opt_label_afcBoxHei.setObjectName("opt_label_afcBoxHei")
        self.opt_horizontalLayout_7.addWidget(self.opt_label_afcBoxHei)
        self.opt_spinBox_widthValue = QtWidgets.QSpinBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_spinBox_widthValue.setFont(font)
        self.opt_spinBox_widthValue.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_spinBox_widthValue.setMaximum(2000)
        self.opt_spinBox_widthValue.setProperty("value", 600)
        self.opt_spinBox_widthValue.setObjectName("opt_spinBox_widthValue")
        self.opt_horizontalLayout_7.addWidget(self.opt_spinBox_widthValue)
        self.layoutWidget7 = QtWidgets.QWidget(self.opt_groupBox_bot)
        self.layoutWidget7.setGeometry(QtCore.QRect(50, 80, 177, 25))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.opt_horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.opt_horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.opt_horizontalLayout_8.setObjectName("opt_horizontalLayout_8")
        self.opt_label_afcBoxWid = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_label_afcBoxWid.setFont(font)
        self.opt_label_afcBoxWid.setScaledContents(False)
        self.opt_label_afcBoxWid.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_label_afcBoxWid.setWordWrap(True)
        self.opt_label_afcBoxWid.setObjectName("opt_label_afcBoxWid")
        self.opt_horizontalLayout_8.addWidget(self.opt_label_afcBoxWid)
        self.opt_spinBox_heightValue = QtWidgets.QSpinBox(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_spinBox_heightValue.setFont(font)
        self.opt_spinBox_heightValue.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_spinBox_heightValue.setMaximum(2000)
        self.opt_spinBox_heightValue.setProperty("value", 300)
        self.opt_spinBox_heightValue.setObjectName("opt_spinBox_heightValue")
        self.opt_horizontalLayout_8.addWidget(self.opt_spinBox_heightValue)
        ######## 설정.오토 포커싱 옵션 설정 end

        ######## 탭 정보 생성 처리
        self.mainTabWidget.addTab(self.tab_ext,"영상검출")
        self.mainTabWidget.addTab(self.tab_afc,"오토포커싱")
        self.mainTabWidget.addTab(self.tab_opt, "설정")

        ######## 폼 액션 처리
        self.verticalLayout_4.addWidget(self.mainTabWidget)
        self.action = QtWidgets.QAction(Form)
        self.action.setObjectName("action")
        self.retranslateUi(Form)
        self.mainTabWidget.setCurrentIndex(0)
        self.opt_comboBox_bufTime.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

        ######## tab key로 인한 이동 순서 설정 start / Form.setTabOrder(A, B) -> Form.setTabOrder(B, C)
        Form.setTabOrder(self.ext_pushButton_localUpload, self.ext_pushButton_urlUpload)
        Form.setTabOrder(self.ext_pushButton_urlUpload, self.ext_pushButton_mdDown)
        Form.setTabOrder(self.ext_pushButton_mdDown, self.ext_pushButton_startExt)
        Form.setTabOrder(self.ext_pushButton_startExt, self.ext_tableWidget_extResultList)
        Form.setTabOrder(self.ext_tableWidget_extResultList, self.ext_pushButton_allClear)
        Form.setTabOrder(self.ext_pushButton_allClear, self.ext_pushButton_selectDelete)
        Form.setTabOrder(self.ext_pushButton_selectDelete, self.ext_pushButton_allSave)
        Form.setTabOrder(self.ext_pushButton_allSave, self.ext_pushButton_selectSave)
        Form.setTabOrder(self.ext_pushButton_selectSave, self.ext_tableWidget_classList)
        Form.setTabOrder(self.ext_tableWidget_classList, self.opt_lineEdit_urlSaveDir)
        Form.setTabOrder(self.opt_lineEdit_urlSaveDir, self.opt_pushButton_urlDownDir)
        Form.setTabOrder(self.opt_pushButton_urlDownDir, self.opt_lineEdit_saveDir)
        Form.setTabOrder(self.opt_lineEdit_saveDir, self.opt_pushButton_saveDir)
        Form.setTabOrder(self.opt_pushButton_saveDir, self.opt_comboBox_downFileFmt)
        Form.setTabOrder(self.opt_comboBox_downFileFmt, self.opt_comboBox_downFileDef)
        Form.setTabOrder(self.opt_comboBox_downFileDef, self.opt_comboBox_coordFmt)
        Form.setTabOrder(self.opt_comboBox_coordFmt, self.opt_comboBox_bufTime)
        Form.setTabOrder(self.opt_comboBox_bufTime, self.opt_spinBox_widthValue)
        Form.setTabOrder(self.opt_spinBox_widthValue, self.opt_spinBox_heightValue)
        ######## tab key로 인한 이동 순서 설정 end


    def retranslateUi(self, Form):
        """
        	# 테이블 데이터 / 버튼명 데이터  label text 데이터 입력 처리부
        	# 확인 후 해당 형태로 데이터 입력
        """
        # 어플리케이션 네임
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Human?", None, -1))

        # 영상검출 버튼 및  비디오 제어 라벨 설정
        self.ext_pushButton_localUpload.setText(QtWidgets.QApplication.translate("Form", "로컬 업로드", None, -1))
        self.ext_pushButton_mdDown.setText(QtWidgets.QApplication.translate("Form", "영상 내려받기", None, -1))
        self.ext_pushButton_urlUpload.setText(QtWidgets.QApplication.translate("Form", "URL 업로드", None, -1))
        self.ext_label_extMd.setText(QtWidgets.QApplication.translate("Form", "Video Area", None, -1))
        self.ext_pushButton_play.setText(QtWidgets.QApplication.translate("Form", "play", None, -1))
        self.ext_pushButton_pause.setText(QtWidgets.QApplication.translate("Form", "pause", None, -1))
        self.ext_pushButton_stop.setText(QtWidgets.QApplication.translate("Form", "stop", None, -1))
        self.ext_video_time.setText(QtWidgets.QApplication.translate("Form", "000:00:00 / 000:00:00", None, -1))
        self.ext_pushButton_allClear.setText(QtWidgets.QApplication.translate("Form","초기화",None,-1))
        self.ext_pushButton_selectDelete.setText(QtWidgets.QApplication.translate("Form","선택 삭제",None,-1))
        self.ext_pushButton_allSave.setText(QtWidgets.QApplication.translate("Form","전체 내려받기",None,-1))
        self.ext_pushButton_selectSave.setText(QtWidgets.QApplication.translate("Form","선택 내려받기",None,-1))
        self.ext_label_classList.setText(QtWidgets.QApplication.translate("Form","검출 대상 리스트",None,-1))
        self.ext_pushButton_startExt.setText(QtWidgets.QApplication.translate("Form","검출 시작",None,-1))


        # 영상검출.검출결과리스트 테이블 헤더 설정
        self.ext_label_extResultList.setText(QtWidgets.QApplication.translate("Form", "검출 내역", None, -1))
        self.ext_tableWidget_extResultList.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Form", "썸네일", None, -1))
        self.ext_tableWidget_extResultList.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Form", "검출구간", None, -1))
        self.ext_tableWidget_extResultList.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Form", "검출구간수정", None, -1))
        self.ext_tableWidget_extResultList.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Form", "라벨명", None, -1))
        self.ext_tableWidget_extResultList.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Form", "기타정보", None, -1))
        self.ext_tableWidget_extResultList.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("Form", "선택", None, -1))
        __sortingEnabled = self.ext_tableWidget_extResultList.isSortingEnabled()
        self.ext_tableWidget_extResultList.setSortingEnabled(False)

        # 영상검출.검출결과리스트 테이블 임의 Row 값 입력 (해당 내역 참조해서 값 입력 function 생성)
        self.ext_tableWidget_extResultList.item(0, 0).setText(QtWidgets.QApplication.translate("Form", "썸네일 이미지 추가예정", None, -1))
        self.ext_tableWidget_extResultList.item(0, 1).setText(QtWidgets.QApplication.translate("Form", "00:22-00:27", None, -1))
        self.ext_tableWidget_extResultList.item(0, 2).setText(QtWidgets.QApplication.translate("Form", "셀렉트바 추가", None, -1))
        self.ext_tableWidget_extResultList.item(0, 3).setText(QtWidgets.QApplication.translate("Form", "아이린", None, -1))
        self.ext_tableWidget_extResultList.item(0, 4).setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.ext_tableWidget_extResultList.item(0, 5).setText(QtWidgets.QApplication.translate("Form", "체크박스 추가", None, -1))
        self.ext_tableWidget_extResultList.item(1, 0).setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.ext_tableWidget_extResultList.item(1, 1).setText(QtWidgets.QApplication.translate("Form", "00:35-00:40", None, -1))
        self.ext_tableWidget_extResultList.item(1, 2).setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.ext_tableWidget_extResultList.item(1, 3).setText(QtWidgets.QApplication.translate("Form", "아이린", None, -1))
        self.ext_tableWidget_extResultList.item(1, 4).setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.ext_tableWidget_extResultList.item(1, 5).setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.ext_tableWidget_extResultList.item(2, 0).setText(QtWidgets.QApplication.translate("Form", "2", None, -1))
        self.ext_tableWidget_extResultList.item(2, 1).setText(QtWidgets.QApplication.translate("Form", "00:50-00:55", None, -1))
        self.ext_tableWidget_extResultList.item(2, 2).setText(QtWidgets.QApplication.translate("Form", "2", None, -1))
        self.ext_tableWidget_extResultList.item(2, 3).setText(QtWidgets.QApplication.translate("Form", "아이린", None, -1))
        self.ext_tableWidget_extResultList.item(2, 4).setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.ext_tableWidget_extResultList.item(2, 5).setText(QtWidgets.QApplication.translate("Form", "2", None, -1))
        self.ext_tableWidget_extResultList.item(3, 0).setText(QtWidgets.QApplication.translate("Form", "3", None, -1))
        self.ext_tableWidget_extResultList.item(3, 1).setText(QtWidgets.QApplication.translate("Form", "01:13-01:18", None, -1))
        self.ext_tableWidget_extResultList.item(3, 2).setText(QtWidgets.QApplication.translate("Form", "3", None, -1))
        self.ext_tableWidget_extResultList.item(3, 3).setText(QtWidgets.QApplication.translate("Form", "아이린", None, -1))
        self.ext_tableWidget_extResultList.item(3, 4).setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.ext_tableWidget_extResultList.item(3, 5).setText(QtWidgets.QApplication.translate("Form", "3", None, -1))
        self.ext_tableWidget_extResultList.setSortingEnabled(__sortingEnabled)



        # 오토 포커싱탭 버튼 및 라벨 설정
        self.afc_pushButton_localUpload.setText(QtWidgets.QApplication.translate("Form", "로컬 업로드", None, -1))
        self.afc_pushButton_mdDown.setText(QtWidgets.QApplication.translate("Form", "영상 내려받기", None, -1))
        self.afc_pushButton_urlUpload.setText(QtWidgets.QApplication.translate("Form", "URL 업로드", None, -1))
        self.afc_label_before_Md.setText(QtWidgets.QApplication.translate("Form", "Video Area", None, -1))
        self.afc_pushButton_play.setText(QtWidgets.QApplication.translate("Form", "play", None, -1))
        self.afc_pushButton_pause.setText(QtWidgets.QApplication.translate("Form", "pause", None, -1))
        self.afc_pushButton_stop.setText(QtWidgets.QApplication.translate("Form", "stop", None, -1))
        self.afc_before_time.setText(QtWidgets.QApplication.translate("Form", "000:00:00 / 000:00:00", None, -1))
        self.afc_label_after_Md.setText(QtWidgets.QApplication.translate("Form", "Video Area", None, -1))
        self.afc_pushButton_play_2.setText(QtWidgets.QApplication.translate("Form", "play", None, -1))
        self.afc_pushButton_pause_2.setText(QtWidgets.QApplication.translate("Form", "pause", None, -1))
        self.afc_pushButton_stop_2.setText(QtWidgets.QApplication.translate("Form", "stop", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "000:00:00 / 000:00:00", None, -1))
        self.afc_label_classList.setText(QtWidgets.QApplication.translate("Form", "검출 대상 리스트", None, -1))
        self.afc_pushButton_startExt.setText(QtWidgets.QApplication.translate("Form", "검출 시작", None, -1))

        # 설정탭 버튼 및 라벨
        self.opt_groupBox_top.setTitle(QtWidgets.QApplication.translate("Form", "공통 옵션 설정", None, -1))
        self.opt_label_saveFmt.setText(QtWidgets.QApplication.translate("Form", "내려받기 확장자", None, -1))
        self.opt_comboBox_downFileFmt.setItemText(24, QtWidgets.QApplication.translate("Form", "확장자 선택", None, -1))
        self.opt_comboBox_downFileFmt.setItemText(25, QtWidgets.QApplication.translate("Form", "mp4", None, -1))
        self.opt_label_coordFmt.setText(QtWidgets.QApplication.translate("Form", "좌표파일 확장자 선택", None, -1))
        self.opt_comboBox_coordFmt.setItemText(26, QtWidgets.QApplication.translate("Form", "확장자 선택", None, -1))
        self.opt_label_saveMdQual.setText(QtWidgets.QApplication.translate("Form", "내려받기 화질 선택", None, -1))
        self.opt_comboBox_downFileDef.setItemText(27, QtWidgets.QApplication.translate("Form", "화질 선택", None, -1))
        self.opt_label_urlSaveDir.setText(QtWidgets.QApplication.translate("Form", "URL 저장 파일 경로", None, -1))
        self.opt_pushButton_urlDownDir.setText(QtWidgets.QApplication.translate("Form", "폴더찾기", None, -1))
        self.opt_label_localSaveDir.setText(QtWidgets.QApplication.translate("Form", "내려받기 저장 경로", None, -1))
        self.opt_pushButton_saveDir.setText(QtWidgets.QApplication.translate("Form", "폴더찾기", None, -1))
        self.opt_groupBox_mid.setTitle(QtWidgets.QApplication.translate("Form", "영상 검출 옵션 설정", None, -1))
        self.opt_groupBox_4.setTitle(QtWidgets.QApplication.translate("Form", "GroupBox", None, -1))
        self.opt_label_cn1.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" color:#ff0000;\">※ 검출 내역 한 건당 설정 할 수 있는 버퍼의 범위는 00:01 ~ 00:05 초 사이로 설정 할 수 있습니다.</span></p></body></html>", None, -1))
        self.opt_label_extButTm.setText(QtWidgets.QApplication.translate("Form", "추출 영상 버퍼 시간", None, -1))
        self.opt_comboBox_bufTime.setItemText(28, QtWidgets.QApplication.translate("Form", "버퍼(초)선택", None, -1))
        self.opt_comboBox_bufTime.setItemText(29, QtWidgets.QApplication.translate("Form", "1초", None, -1))
        self.opt_comboBox_bufTime.setItemText(30, QtWidgets.QApplication.translate("Form", "3초", None, -1))
        self.opt_comboBox_bufTime.setItemText(31, QtWidgets.QApplication.translate("Form", "5초", None, -1))
        self.opt_groupBox_bot.setTitle(QtWidgets.QApplication.translate("Form", "오토 포커싱 옵션 설정", None, -1))
        self.opt_label_cn2.setText(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><span style=\" color:#ff0000;\">※ 포커싱 박스의 넓이 및 높이는 포커싱 영상의 해상도 보다 클 수 없습니다.</span></p></body></html>", None, -1))
        self.opt_label_afcBoxHei.setText(QtWidgets.QApplication.translate("Form", "포커싱 박스 높이", None, -1))
        self.opt_label_afcBoxWid.setText(QtWidgets.QApplication.translate("Form", "포커싱 박스 넓이", None, -1))
        self.action.setText(QtWidgets.QApplication.translate("Form", "테스트", None, -1))
        self.action.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>툴팁화면</p></body></html>", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

